export const GOOGLE_CLIENT_ID_ENV = "GOOGLE_OAUTH_CLIENT_ID";
export const GOOGLE_CLIENT_SECRET_ENV = "GOOGLE_OAUTH_CLIENT_SECRET";
export const GOOGLE_REFRESH_TOKEN_ENV = "GOOGLE_OAUTH_REFRESH_TOKEN";

export const GOOGLE_CLOUD_CLIENT_ID_ENV = "GOOGLE_CLOUD_OAUTH_CLIENT_ID";
export const GOOGLE_CLOUD_CLIENT_SECRET_ENV = "GOOGLE_CLOUD_OAUTH_CLIENT_SECRET";
export const GOOGLE_CLOUD_REFRESH_TOKEN_ENV = "GOOGLE_CLOUD_OAUTH_REFRESH_TOKEN";
export const GOOGLE_CLOUD_ACCOUNT_EMAIL_ENV = "GOOGLE_CLOUD_OAUTH_ACCOUNT_EMAIL";
