import {
  HIVE_COMPUTE_ATTESTATION_POLICY_URL_ENV,
  HIVE_COMPUTE_CONFIDENTIAL_MODE_ENV,
  HIVE_COMPUTE_DEFAULT_MODEL,
  HIVE_COMPUTE_GATEWAY_URL_ENV,
  HIVE_COMPUTE_MPP_POLICY_URL_ENV,
  HIVE_COMPUTE_MPP_REQUIRE_SESSION_ENV,
  HIVE_COMPUTE_MPP_SESSION_TOKEN_ENV,
  HIVE_COMPUTE_PAYMENT_RAIL_ENV,
  HIVE_COMPUTE_PRODUCT_NAME,
  HIVE_COMPUTE_TEE_ATTESTATION_COMMAND_ENV,
  HIVE_COMPUTE_TEE_ATTESTATION_FILE_ENV,
  HIVE_COMPUTE_TEE_ATTESTATION_FORMAT_ENV,
  HIVE_COMPUTE_TEE_DECRYPTION_PRIVATE_KEY_FILE_ENV,
  HIVE_COMPUTE_TEE_ENCRYPTION_PUBLIC_KEY_ENV,
  HIVE_COMPUTE_TEE_IMAGE_DIGEST_ENV,
  HIVE_COMPUTE_TEE_MEASUREMENT_ENV,
  HIVE_COMPUTE_TEE_PAYLOAD_KEY_ENV,
  HIVE_COMPUTE_TEE_PROVIDER_ENV,
  HIVE_COMPUTE_WORKER_PACKAGE_NAME,
  HIVE_COMPUTE_WORKER_REQUIRE_PAYMENT_PROOF_ENV,
  HIVE_COMPUTE_WORKER_VERSION,
  HIVE_COMPUTE_WORKER_TOKEN_ENV,
} from "@/lib/config/hive-compute-marketplace";

export function hiveComputeWorkerPackageJson() {
  return `${JSON.stringify({
    name: HIVE_COMPUTE_WORKER_PACKAGE_NAME,
    version: HIVE_COMPUTE_WORKER_VERSION,
    private: true,
    type: "module",
    description: "Optional HivemindOS marketplace worker for renting out local GPUs through a compatible gateway.",
    scripts: {
      start: "node worker.mjs",
    },
    dependencies: {
      "ws": "^8.18.0",
    },
    engines: {
      node: ">=20",
    },
  }, null, 2)}\n`;
}

export function hiveComputeWorkerReadme() {
  return `# ${HIVE_COMPUTE_PRODUCT_NAME} Worker

This optional module lets this machine accept marketplace inference jobs from a
compatible Hive Compute gateway and serve them with local Ollama or
OpenAI-compatible models such as LM Studio.

## Configure

Set these in the shared hive env, project env, or process env:

- ${HIVE_COMPUTE_GATEWAY_URL_ENV}: HTTPS URL of the official or self-hosted gateway.
- ${HIVE_COMPUTE_WORKER_TOKEN_ENV}: worker token issued by that gateway.
- HIVE_COMPUTE_LOCAL_ENGINE: optional, \`ollama\` or \`openai\`; defaults to
  \`openai\` when HIVE_COMPUTE_LOCAL_OPENAI_BASE_URL is set, otherwise
  \`ollama\`.
- OLLAMA_HOST: optional for Ollama mode, defaults to http://127.0.0.1:11434.
- HIVE_COMPUTE_LOCAL_OPENAI_BASE_URL: optional for LM Studio/OpenAI-compatible
  mode, for example http://127.0.0.1:1234/v1.
- HIVE_COMPUTE_LOCAL_OPENAI_API_KEY: optional bearer token for the local
  OpenAI-compatible server.
- HIVE_COMPUTE_MODELS: optional comma-separated model routes to advertise.
- HIVE_COMPUTE_MODEL_MAP_JSON: optional JSON mapping route ids to local model
  ids.
- HIVE_COMPUTE_DEFAULT_OPENAI_MODEL: optional default local model for
  OpenAI-compatible mode.
- HIVE_COMPUTE_WORKER_WS_PATH: optional, defaults to /hive-compute/worker/ws.
- HIVE_COMPUTE_WORKER_MAX_CONCURRENCY: optional advertised concurrency limit.
- ${HIVE_COMPUTE_PAYMENT_RAIL_ENV}: \`x402\`, \`mpp\`, \`prepaid\`, or
  \`self-hosted\`.
- ${HIVE_COMPUTE_MPP_POLICY_URL_ENV}: optional hosted MPP session policy URL.
- ${HIVE_COMPUTE_MPP_SESSION_TOKEN_ENV}: optional session authorization from a
  compatible gateway.
- ${HIVE_COMPUTE_MPP_REQUIRE_SESSION_ENV}: set to \`1\` to reject jobs without
  MPP session proof.
- ${HIVE_COMPUTE_CONFIDENTIAL_MODE_ENV}: optional, set to \`tee-attested\` only
  when this worker runs inside a verifiable confidential-compute runtime.
- ${HIVE_COMPUTE_TEE_PROVIDER_ENV}: optional provider label such as \`sev-snp\`,
  \`tdx\`, \`nitro\`, or \`nvidia-cc\`.
- ${HIVE_COMPUTE_ATTESTATION_POLICY_URL_ENV}: optional hosted attestation policy
  used by compatible gateways for verified-only routing.
- ${HIVE_COMPUTE_TEE_ATTESTATION_FILE_ENV}: optional TEE evidence/quote file.
- ${HIVE_COMPUTE_TEE_ATTESTATION_COMMAND_ENV}: optional command that emits fresh
  attestation evidence. The worker passes the challenge nonce in
  \`HIVE_COMPUTE_TEE_NONCE\`.
- ${HIVE_COMPUTE_TEE_ENCRYPTION_PUBLIC_KEY_ENV}: public key advertised to the
  gateway for encrypted prompt delivery.
- ${HIVE_COMPUTE_TEE_DECRYPTION_PRIVATE_KEY_FILE_ENV}: optional RSA-OAEP or
  X25519 private key PEM path for encrypted job payloads.
- ${HIVE_COMPUTE_TEE_PAYLOAD_KEY_ENV}: optional sealed symmetric AES-256-GCM key
  for encrypted job payloads.

Standard workers receive prompt contents for jobs they accept. Hardware-enforced
privacy requires gateway-verified TEE attestation plus encrypted prompt and
output delivery; the worker can collect evidence, decrypt encrypted payloads,
and encrypt responses only when the runtime provides the required enclave
keys/evidence.

## Run

\`\`\`sh
npm install --omit=dev
hive-env-run -- npm start
\`\`\`
`;
}

export function hiveComputeWorkerNotice() {
  return `Hive Compute Worker

Generated by HivemindOS as an optional installable module. It implements a
small native WebSocket worker protocol compatible with Hive Compute gateways,
with local Ollama and OpenAI-compatible serving adapters.
TEE privacy, x402 settlement, MPP sessions, bonds, payouts, and reputation are
gateway-side capabilities. This worker can enforce gateway-supplied payment
proofs, collect remote-attestation evidence, decrypt encrypted payloads, and
encrypt response output when the enclosing runtime supplies enclave keys.
The public HivemindOS app contains no official marketplace ledger, payout,
quota, entitlement, treasury, or fraud-control authority; official authority
belongs in hosted HivemindOS infrastructure or in a self-hosted operator's own
gateway.
`;
}

export const HIVE_COMPUTE_WORKER_SOURCE = `#!/usr/bin/env node
import { spawnSync } from "node:child_process";
import { constants, createCipheriv, createDecipheriv, createHash, createPrivateKey, createPublicKey, diffieHellman, hkdfSync, privateDecrypt, publicEncrypt, randomBytes } from "node:crypto";
import { readFileSync } from "node:fs";
import os from "node:os";
import WebSocket from "ws";

const VERSION = "${HIVE_COMPUTE_WORKER_VERSION}";
const gateway = requiredEnv("${HIVE_COMPUTE_GATEWAY_URL_ENV}");
const token = requiredEnv("${HIVE_COMPUTE_WORKER_TOKEN_ENV}");
const ollamaHost = (process.env.OLLAMA_HOST || "http://127.0.0.1:11434").replace(/\\/+$/, "");
const openAiBaseUrl = (process.env.HIVE_COMPUTE_LOCAL_OPENAI_BASE_URL || "").replace(/\\/+$/, "");
const openAiApiKey = process.env.HIVE_COMPUTE_LOCAL_OPENAI_API_KEY || "";
const localEngine = normalizeEngine(process.env.HIVE_COMPUTE_LOCAL_ENGINE || (openAiBaseUrl ? "openai" : "ollama"));
const workerName = process.env.HIVE_COMPUTE_WORKER_NAME || os.hostname();
const workerId = process.env.HIVE_COMPUTE_WORKER_ID || workerName;
const advertisedModels = splitList(process.env.HIVE_COMPUTE_MODELS || "${HIVE_COMPUTE_DEFAULT_MODEL},hive-compute/fast");
const modelMap = parseModelMap(process.env.HIVE_COMPUTE_MODEL_MAP_JSON || "");
const wsPath = process.env.HIVE_COMPUTE_WORKER_WS_PATH || "/hive-compute/worker/ws";
const maxConcurrency = positiveInteger(process.env.HIVE_COMPUTE_WORKER_MAX_CONCURRENCY, 1);
const hostWhen = process.env.HIVE_COMPUTE_WORKER_HOST_WHEN || "idle";
const paymentRail = normalizeRail(process.env.${HIVE_COMPUTE_PAYMENT_RAIL_ENV} || "x402");
const mppPolicyUrl = process.env.${HIVE_COMPUTE_MPP_POLICY_URL_ENV} || "";
const mppSessionToken = process.env.${HIVE_COMPUTE_MPP_SESSION_TOKEN_ENV} || "";
const mppRequireSession = booleanEnv(process.env.${HIVE_COMPUTE_MPP_REQUIRE_SESSION_ENV}, paymentRail === "mpp");
const requirePaymentProof = booleanEnv(process.env.${HIVE_COMPUTE_WORKER_REQUIRE_PAYMENT_PROOF_ENV}, mppRequireSession || paymentRail === "mpp");
const confidentialMode = process.env.${HIVE_COMPUTE_CONFIDENTIAL_MODE_ENV} || "standard";
const teeProvider = process.env.${HIVE_COMPUTE_TEE_PROVIDER_ENV} || "";
const attestationPolicyUrl = process.env.${HIVE_COMPUTE_ATTESTATION_POLICY_URL_ENV} || "";
const attestationFile = process.env.${HIVE_COMPUTE_TEE_ATTESTATION_FILE_ENV} || "";
const attestationCommand = process.env.${HIVE_COMPUTE_TEE_ATTESTATION_COMMAND_ENV} || "";
const attestationFormat = process.env.${HIVE_COMPUTE_TEE_ATTESTATION_FORMAT_ENV} || "raw";
const teeMeasurement = process.env.${HIVE_COMPUTE_TEE_MEASUREMENT_ENV} || "";
const teeImageDigest = process.env.${HIVE_COMPUTE_TEE_IMAGE_DIGEST_ENV} || "";
const teeEncryptionPublicKey = process.env.${HIVE_COMPUTE_TEE_ENCRYPTION_PUBLIC_KEY_ENV} || "";
const teePrivateKeyFile = process.env.${HIVE_COMPUTE_TEE_DECRYPTION_PRIVATE_KEY_FILE_ENV} || "";
const teePayloadKey = process.env.${HIVE_COMPUTE_TEE_PAYLOAD_KEY_ENV} || "";
let socket = null;
let reconnectDelayMs = 1000;

connect();

const registerInterval = setInterval(() => void register(), 30000);
registerInterval.unref && registerInterval.unref();
const heartbeatInterval = setInterval(() => {
  emit("worker.heartbeat", {
    workerId,
    workerName,
    models: advertisedModels,
    engine: localEngine,
    localBaseUrl: localEngine === "openai" ? openAiBaseUrl : ollamaHost,
    capabilities: workerCapabilities(),
    version: VERSION,
    at: new Date().toISOString(),
  });
}, 15000);
heartbeatInterval.unref && heartbeatInterval.unref();

function connect() {
  const url = websocketUrl(joinUrl(gateway, wsPath));
  socket = new WebSocket(url, {
    headers: { Authorization: "Bearer " + token },
  });

  socket.on("open", () => {
    reconnectDelayMs = 1000;
    void register();
    console.log("[hive-compute] connected", url);
  });

  socket.on("message", (raw) => {
    const message = parseServerMessage(raw);
    if (!message) return;
    handleServerMessage(message).catch((error) => {
      console.error("[hive-compute] server message failed:", error instanceof Error ? error.message : String(error));
    });
  });

  socket.on("close", (code, reason) => {
    console.log("[hive-compute] disconnected", code, String(reason || ""));
    scheduleReconnect();
  });

  socket.on("error", (error) => {
    console.error("[hive-compute] connection failed:", error.message);
  });
}

function scheduleReconnect() {
  const delay = reconnectDelayMs;
  reconnectDelayMs = Math.min(reconnectDelayMs * 2, 30000);
  const timer = setTimeout(connect, delay);
  timer.unref && timer.unref();
}

async function handleServerMessage(message) {
  if (message.type === "server.ready" || message.type === "worker.registered" || message.type === "worker.attestation.accepted") return;
  if (message.type === "worker.attestation.challenge" || message.type === "attestation.challenge") {
    const nonce = message.payload && typeof message.payload === "object" ? String(message.payload.nonce || "") : "";
    emit("worker.attestation", { workerId, attestation: collectAttestation(nonce) });
    return;
  }
  if (message.type === "job.assign") {
    try {
      await runJob(message.payload);
    } catch (error) {
      emitJobError(message.payload && message.payload.jobId, error);
    }
    return;
  }
  if (message.type === "worker.earning") {
    const earning = message.payload;
    if (!earning || typeof earning !== "object") return;
    const amount = earning.usdMicro ? "$" + (Number(earning.usdMicro) / 1_000_000).toFixed(6) : "pending";
    console.log("[hive-compute] earning", earning.jobId || "", amount);
    return;
  }
  if (message.type === "server.error") {
    console.error("[hive-compute] server error:", JSON.stringify(message.payload || {}));
  }
}

async function register() {
  emit("worker.register", {
    workerId,
    workerName,
    models: advertisedModels,
    capabilities: workerCapabilities(),
    version: VERSION,
  });
}

function workerCapabilities() {
  const attestation = collectAttestation("");
  return {
    chat: true,
    streaming: true,
    engine: localEngine,
    maxConcurrency,
    hostWhen,
    payments: {
      x402: true,
      mpp: Boolean(mppPolicyUrl || mppSessionToken || paymentRail === "mpp"),
      mppPolicyUrl,
      requireSession: mppRequireSession,
    },
    privacy: {
      mode: confidentialMode,
      provider: teeProvider,
      teeAttestation: attestation.ready,
      encryptedPromptDelivery: Boolean(teeEncryptionPublicKey && (teePrivateKeyFile || teePayloadKey)),
      encryptedOutputDelivery: true,
      attestationPolicyUrl,
      encryptionPublicKey: teeEncryptionPublicKey,
      attestation,
    },
  };
}

async function runJob(job) {
  if (!job || typeof job !== "object") throw new Error("Invalid job assignment.");
  validateJobPayment(job);
  const normalizedJob = normalizeEncryptedJob(job);
  const jobId = String(normalizedJob.jobId || normalizedJob.id || "");
  if (!jobId) throw new Error("Job assignment is missing jobId.");
  const routeModel = String(normalizedJob.model || advertisedModels[0] || "${HIVE_COMPUTE_DEFAULT_MODEL}");
  const localModel = modelMap[routeModel] || modelMap["*"] || defaultLocalModel(routeModel);
  const messages = normalizeMessages(normalizedJob);
  const outputEncryption = outputEncryptionFromJob(normalizedJob);
  console.log("[hive-compute] job", jobId, routeModel, "->", localModel, "(" + localEngine + ")");
  emit("job.accepted", { jobId, workerId, model: routeModel, localModel, engine: localEngine });

  if (localEngine === "openai") {
    await runOpenAICompatibleJob({ jobId, localModel, messages, options: normalizedJob.options, outputEncryption });
    return;
  }
  await runOllamaJob({ jobId, localModel, messages, options: normalizedJob.options, outputEncryption });
}

function validateJobPayment(job) {
  if (!requirePaymentProof) return;
  const payment = job.payment && typeof job.payment === "object" ? job.payment : {};
  const rail = normalizeRail(String(payment.rail || payment.protocol || ""));
  if (mppRequireSession && rail !== "mpp") throw new Error("MPP session payment proof is required.");
  if (rail === "mpp") {
    if (!payment.sessionId && !payment.receipt && !payment.authorization) throw new Error("MPP job is missing session proof.");
    return;
  }
  if (rail === "x402" && (payment.settled === true || payment.authorized === true || payment.receipt)) return;
  if (rail === "prepaid" && (payment.authorized === true || payment.receipt)) return;
  throw new Error("Job is missing a gateway-authorized payment proof.");
}

function outputEncryptionFromJob(job) {
  const privacy = job.privacy && typeof job.privacy === "object" ? job.privacy : {};
  const output = privacy.outputEncryption && typeof privacy.outputEncryption === "object" ? privacy.outputEncryption : {};
  const required = output.required === true;
  if (!required) return null;
  const publicKey = normalizePublicKeyMaterial(String(output.publicKey || ""));
  if (!publicKey) throw new Error("Output encryption is required but no client public key was provided.");
  return {
    required: true,
    algorithm: "rsa-oaep-a256gcm",
    publicKey,
    publicKeySha256: String(output.publicKeySha256 || sha256(publicKey)).trim() || sha256(publicKey),
  };
}

function normalizeEncryptedJob(job) {
  const encrypted = job.encryptedPayload || job.encrypted_payload;
  if (!encrypted) return job;
  const decrypted = decryptPayload(encrypted);
  return { ...job, ...decrypted, encryptedPayload: undefined, encrypted_payload: undefined };
}

function decryptPayload(envelope) {
  if (!envelope || typeof envelope !== "object") throw new Error("Encrypted payload envelope is invalid.");
  const algorithm = String(envelope.algorithm || "").toLowerCase();
  if (algorithm === "dir-a256gcm" || algorithm === "aes-256-gcm") return decryptAesGcm(envelope, directPayloadKey());
  if (algorithm === "rsa-oaep-a256gcm") return decryptRsaOaepAesGcm(envelope);
  if (algorithm === "x25519-chacha20-poly1305") return decryptX25519Chacha(envelope);
  throw new Error("Unsupported encrypted payload algorithm: " + algorithm);
}

function directPayloadKey() {
  if (!teePayloadKey) throw new Error("${HIVE_COMPUTE_TEE_PAYLOAD_KEY_ENV} is required for AES-GCM encrypted payloads.");
  const key = Buffer.from(teePayloadKey, "base64");
  if (key.length !== 32) throw new Error("${HIVE_COMPUTE_TEE_PAYLOAD_KEY_ENV} must decode to 32 bytes.");
  return key;
}

function decryptAesGcm(envelope, key) {
  const nonce = b64(envelope.nonce || envelope.iv);
  const tag = b64(envelope.tag);
  const ciphertext = b64(envelope.ciphertext);
  const decipher = createDecipheriv("aes-256-gcm", key, nonce);
  if (envelope.aad) decipher.setAAD(Buffer.from(String(envelope.aad)));
  decipher.setAuthTag(tag);
  const plaintext = Buffer.concat([decipher.update(ciphertext), decipher.final()]).toString("utf8");
  return JSON.parse(plaintext);
}

function decryptRsaOaepAesGcm(envelope) {
  if (!teePrivateKeyFile) throw new Error("${HIVE_COMPUTE_TEE_DECRYPTION_PRIVATE_KEY_FILE_ENV} is required for RSA-OAEP encrypted payloads.");
  const privateKey = readFileSync(teePrivateKeyFile, "utf8");
  const key = privateDecrypt({
    key: privateKey,
    padding: constants.RSA_PKCS1_OAEP_PADDING,
    oaepHash: "sha256",
  }, b64(envelope.encryptedKey || envelope.encrypted_key));
  return decryptAesGcm(envelope, key);
}

function decryptX25519Chacha(envelope) {
  if (!teePrivateKeyFile) throw new Error("${HIVE_COMPUTE_TEE_DECRYPTION_PRIVATE_KEY_FILE_ENV} is required for X25519 encrypted payloads.");
  const privateKey = createPrivateKey(readFileSync(teePrivateKeyFile, "utf8"));
  const peerPublicKey = createPublicKey({
    key: { kty: "OKP", crv: "X25519", x: String(envelope.ephemeralPublicKey || envelope.ephemeral_public_key || "") },
    format: "jwk",
  });
  const shared = diffieHellman({ privateKey, publicKey: peerPublicKey });
  const salt = envelope.salt ? b64(envelope.salt) : Buffer.alloc(0);
  const info = Buffer.from(String(envelope.info || "hivemindos-hive-compute-v1"));
  const key = Buffer.from(hkdfSync("sha256", shared, salt, info, 32));
  const nonce = b64(envelope.nonce);
  const tag = b64(envelope.tag);
  const ciphertext = b64(envelope.ciphertext);
  const decipher = createDecipheriv("chacha20-poly1305", key, nonce, { authTagLength: 16 });
  if (envelope.aad) decipher.setAAD(Buffer.from(String(envelope.aad)));
  decipher.setAuthTag(tag);
  const plaintext = Buffer.concat([decipher.update(ciphertext), decipher.final()]).toString("utf8");
  return JSON.parse(plaintext);
}

function emitJobToken(input, tokenText, sequence) {
  if (!tokenText) return;
  if (!input.outputEncryption) {
    emit("job.token", { jobId: input.jobId, token: tokenText });
    return;
  }
  emit("job.encrypted_token", {
    jobId: input.jobId,
    encryptedToken: encryptOutputPayload(input.outputEncryption, {
      type: "delta",
      text: tokenText,
      sequence,
    }, outputAad(input.jobId, "delta", sequence)),
  });
}

function emitJobComplete(input, finalText, usage) {
  const finalUsage = usageWithCompletionEstimate(finalText, usage);
  if (!input.outputEncryption) {
    emit("job.complete", { jobId: input.jobId, text: finalText, usage: finalUsage });
    return;
  }
  emit("job.complete", {
    jobId: input.jobId,
    encryptedOutput: encryptOutputPayload(input.outputEncryption, {
      type: "final",
      text: finalText,
    }, outputAad(input.jobId, "final", 0)),
    usage: finalUsage,
    outputEncryption: {
      algorithm: input.outputEncryption.algorithm,
      publicKeySha256: input.outputEncryption.publicKeySha256,
    },
  });
}

function usageWithCompletionEstimate(text, usage) {
  const normalized = usage && typeof usage === "object" ? { ...usage } : {};
  if (!Number.isFinite(Number(normalized.completionTokens)) || Number(normalized.completionTokens) <= 0) {
    normalized.completionTokens = estimateTokens(text);
  }
  return normalized;
}

function encryptOutputPayload(outputEncryption, payload, aad) {
  if (outputEncryption.algorithm !== "rsa-oaep-a256gcm") throw new Error("Unsupported output encryption algorithm.");
  const key = randomBytes(32);
  const nonce = randomBytes(12);
  const cipher = createCipheriv("aes-256-gcm", key, nonce);
  cipher.setAAD(Buffer.from(aad));
  const ciphertext = Buffer.concat([
    cipher.update(JSON.stringify(payload), "utf8"),
    cipher.final(),
  ]);
  const tag = cipher.getAuthTag();
  const encryptedKey = publicEncrypt({
    key: outputEncryption.publicKey,
    padding: constants.RSA_PKCS1_OAEP_PADDING,
    oaepHash: "sha256",
  }, key);
  return {
    algorithm: "rsa-oaep-a256gcm",
    encryptedKey: encryptedKey.toString("base64"),
    nonce: nonce.toString("base64"),
    tag: tag.toString("base64"),
    ciphertext: ciphertext.toString("base64"),
    aad,
    publicKeySha256: outputEncryption.publicKeySha256,
    sequence: payload.sequence,
  };
}

function outputAad(jobId, kind, sequence) {
  return "hivemindos-hive-compute-output:" + jobId + ":" + kind + ":" + sequence;
}

function normalizePublicKeyMaterial(value) {
  const trimmed = String(value || "").trim().replace(/\\\\n/g, "\\n");
  if (!trimmed) return "";
  if (trimmed.includes("-----BEGIN PUBLIC KEY-----")) return trimmed;
  const compact = trimmed.replace(/\\s+/g, "");
  return "-----BEGIN PUBLIC KEY-----\\n" + (compact.match(/.{1,64}/g) || [compact]).join("\\n") + "\\n-----END PUBLIC KEY-----";
}

function collectAttestation(nonce) {
  const evidence = readAttestationEvidence(nonce);
  const evidenceHash = evidence ? sha256(evidence) : "";
  return {
    ready: confidentialMode === "tee-attested" && Boolean(teeProvider && evidenceHash),
    mode: confidentialMode,
    provider: teeProvider,
    format: attestationFormat,
    nonce: nonce || undefined,
    evidenceHash,
    evidenceLength: evidence ? evidence.length : 0,
    evidenceBase64: evidence && evidence.length <= 65536 ? evidence.toString("base64") : undefined,
    evidenceSource: attestationCommand ? "command" : attestationFile ? "file" : undefined,
    measurement: teeMeasurement || undefined,
    imageDigest: teeImageDigest || undefined,
    encryptionPublicKey: teeEncryptionPublicKey || undefined,
    collectedAt: new Date().toISOString(),
  };
}

function readAttestationEvidence(nonce) {
  try {
    if (attestationCommand) {
      const result = spawnSync(attestationCommand, {
        shell: true,
        timeout: 10_000,
        maxBuffer: 256 * 1024,
        env: { ...process.env, HIVE_COMPUTE_TEE_NONCE: nonce || "" },
      });
      if (result.status !== 0) return null;
      return Buffer.from(result.stdout || result.stderr || "");
    }
    if (attestationFile) return readFileSync(attestationFile);
  } catch {
    return null;
  }
  return null;
}

async function runOllamaJob(input) {
  const response = await fetch(joinUrl(ollamaHost, "/api/chat"), {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      model: input.localModel,
      messages: input.messages,
      stream: true,
      options: input.options && typeof input.options === "object" ? input.options : undefined,
    }),
  });
  if (!response.ok || !response.body) {
    const text = await response.text().catch(() => "");
    throw new Error("Ollama returned HTTP " + response.status + (text ? ": " + text.slice(0, 400) : ""));
  }

  let finalText = "";
  const decoder = new TextDecoder();
  let buffer = "";
  let sequence = 0;
  for await (const chunk of response.body) {
    buffer += decoder.decode(chunk, { stream: true });
    const lines = buffer.split(/\\r?\\n/);
    buffer = lines.pop() || "";
    for (const line of lines) {
      const trimmed = line.trim();
      if (!trimmed) continue;
      const payload = JSON.parse(trimmed);
      const tokenText = payload.message && typeof payload.message.content === "string" ? payload.message.content : "";
      if (tokenText) {
        finalText += tokenText;
        emitJobToken(input, tokenText, sequence++);
      }
      if (payload.done) {
        emitJobComplete(input, finalText, payload.eval_count || payload.prompt_eval_count ? {
            promptTokens: payload.prompt_eval_count || 0,
            completionTokens: payload.eval_count || 0,
          } : undefined);
        console.log("[hive-compute] completed", input.jobId);
        return;
      }
    }
  }
  emitJobComplete(input, finalText);
}

async function runOpenAICompatibleJob(input) {
  if (!openAiBaseUrl) throw new Error("HIVE_COMPUTE_LOCAL_OPENAI_BASE_URL is required when HIVE_COMPUTE_LOCAL_ENGINE=openai.");
  const headers = { "Content-Type": "application/json" };
  if (openAiApiKey) headers.Authorization = "Bearer " + openAiApiKey;
  const response = await fetch(joinUrl(openAiBaseUrl, "/chat/completions"), {
    method: "POST",
    headers,
    body: JSON.stringify({
      model: input.localModel,
      messages: input.messages,
      stream: true,
      ...openAIOptions(input.options),
    }),
  });
  if (!response.ok || !response.body) {
    const text = await response.text().catch(() => "");
    throw new Error("OpenAI-compatible server returned HTTP " + response.status + (text ? ": " + text.slice(0, 400) : ""));
  }

  let finalText = "";
  let finalUsage = undefined;
  const decoder = new TextDecoder();
  let buffer = "";
  let sequence = 0;
  for await (const chunk of response.body) {
    buffer += decoder.decode(chunk, { stream: true });
    const lines = buffer.split(/\\r?\\n/);
    buffer = lines.pop() || "";
    for (const line of lines) {
      const trimmed = line.trim();
      if (!trimmed || !trimmed.startsWith("data:")) continue;
      const data = trimmed.slice(5).trim();
      if (!data || data === "[DONE]") {
        emitJobComplete(input, finalText, finalUsage);
        console.log("[hive-compute] completed", input.jobId);
        return;
      }
      const payload = JSON.parse(data);
      if (payload.usage && typeof payload.usage === "object") finalUsage = normalizeOpenAIUsage(payload.usage);
      const choices = Array.isArray(payload.choices) ? payload.choices : [];
      for (const choice of choices) {
        const delta = choice && typeof choice === "object" ? choice.delta || choice.message || {} : {};
        const tokenText = typeof delta.content === "string"
          ? delta.content
          : Array.isArray(delta.content)
            ? delta.content.map((part) => typeof part?.text === "string" ? part.text : "").join("")
            : "";
        if (!tokenText) continue;
        finalText += tokenText;
        emitJobToken(input, tokenText, sequence++);
      }
    }
  }
  emitJobComplete(input, finalText, finalUsage);
}

function normalizeMessages(job) {
  if (Array.isArray(job.messages)) {
    return job.messages
      .filter((message) => message && typeof message === "object")
      .map((message) => ({
        role: typeof message.role === "string" ? message.role : "user",
        content: typeof message.content === "string" ? message.content : JSON.stringify(message.content || ""),
      }));
  }
  const prompt = typeof job.prompt === "string" ? job.prompt : "";
  if (!prompt) throw new Error("Job assignment is missing messages or prompt.");
  return [{ role: "user", content: prompt }];
}

function emitJobError(jobId, error) {
  const message = error instanceof Error ? error.message : String(error);
  console.error("[hive-compute] job failed", jobId || "", message);
  if (jobId) emit("job.error", { jobId, error: message });
}

function emit(type, payload) {
  if (!socket || socket.readyState !== WebSocket.OPEN) return false;
  socket.send(JSON.stringify({ type, payload }));
  return true;
}

function parseServerMessage(raw) {
  try {
    const text = Buffer.isBuffer(raw) ? raw.toString("utf8") : String(raw);
    const parsed = JSON.parse(text);
    return parsed && typeof parsed === "object" ? parsed : null;
  } catch {
    return null;
  }
}

function openAIOptions(options) {
  const source = options && typeof options === "object" ? options : {};
  const next = {};
  if (typeof source.temperature === "number") next.temperature = source.temperature;
  if (Number.isFinite(Number(source.num_predict)) && Number(source.num_predict) > 0) {
    next.max_tokens = Math.floor(Number(source.num_predict));
  }
  if (Number.isFinite(Number(source.max_tokens)) && Number(source.max_tokens) > 0) {
    next.max_tokens = Math.floor(Number(source.max_tokens));
  }
  return next;
}

function normalizeOpenAIUsage(usage) {
  if (!usage || typeof usage !== "object") return undefined;
  const promptTokens = Number(usage.prompt_tokens ?? usage.promptTokens ?? 0);
  const completionTokens = Number(usage.completion_tokens ?? usage.completionTokens ?? 0);
  const normalized = {};
  if (Number.isFinite(promptTokens) && promptTokens > 0) normalized.promptTokens = Math.floor(promptTokens);
  if (Number.isFinite(completionTokens) && completionTokens > 0) normalized.completionTokens = Math.floor(completionTokens);
  return Object.keys(normalized).length ? normalized : undefined;
}

function defaultLocalModel(routeModel) {
  if (localEngine === "openai") {
    return process.env.HIVE_COMPUTE_DEFAULT_OPENAI_MODEL || process.env.HIVE_COMPUTE_DEFAULT_LM_STUDIO_MODEL || routeModel;
  }
  if (/deep|large|70b/i.test(routeModel)) return "llama3.3:70b";
  return process.env.HIVE_COMPUTE_DEFAULT_OLLAMA_MODEL || "llama3.2:3b";
}

function normalizeEngine(value) {
  const normalized = String(value || "").trim().toLowerCase();
  if (normalized === "openai" || normalized === "lmstudio" || normalized === "lm-studio") return "openai";
  return "ollama";
}

function parseModelMap(raw) {
  if (!raw.trim()) return {};
  try {
    const parsed = JSON.parse(raw);
    return parsed && typeof parsed === "object" ? parsed : {};
  } catch (error) {
    console.warn("[hive-compute] ignoring invalid HIVE_COMPUTE_MODEL_MAP_JSON:", error.message);
    return {};
  }
}

function splitList(value) {
  return value.split(",").map((item) => item.trim()).filter(Boolean);
}

function positiveInteger(value, fallback) {
  const number = Number(value);
  return Number.isFinite(number) && number > 0 ? Math.floor(number) : fallback;
}

function estimateTokens(text) {
  return Math.max(1, Math.ceil(String(text || "").trim().length / 4));
}

function booleanEnv(value, fallback) {
  if (value === undefined || value === null || value === "") return fallback;
  return ["1", "true", "yes", "on", "enabled"].includes(String(value).trim().toLowerCase());
}

function normalizeRail(value) {
  const normalized = String(value || "").trim().toLowerCase();
  if (normalized === "mpp" || normalized === "prepaid" || normalized === "self-hosted") return normalized;
  return "x402";
}

function requiredEnv(key) {
  const value = process.env[key] && process.env[key].trim();
  if (!value) {
    console.error("[hive-compute] missing required env:", key);
    process.exit(1);
  }
  return value;
}

function joinUrl(base, suffix) {
  return base.replace(/\\/+$/, "") + (suffix.startsWith("/") ? suffix : "/" + suffix);
}

function websocketUrl(url) {
  const parsed = new URL(url);
  parsed.protocol = parsed.protocol === "https:" ? "wss:" : "ws:";
  return parsed.toString();
}

function b64(value) {
  return Buffer.from(String(value || ""), "base64");
}

function sha256(value) {
  return createHash("sha256").update(value).digest("hex");
}
`;
