export const HIVE_CHAT_DOCK_BOTTOM = 26;
export const HIVE_CHAT_DOCK_HEIGHT = 52;
export const HIVE_CHAT_TRANSCRIPT_GAP = 18;

export const HIVE_CHAT_TRANSCRIPT_BOTTOM_OFFSET =
  HIVE_CHAT_DOCK_BOTTOM + HIVE_CHAT_DOCK_HEIGHT + HIVE_CHAT_TRANSCRIPT_GAP;
