// GENERATED by scripts/generate-hive-action-route-policy.mjs — do not edit by hand.
// Re-run that script (or `pnpm guard:hive-action-route-policy` to verify) after
// changing any hive action's route, risk, side effects, or confirmation.
//
// Consumed by src/proxy.ts. Keep this a PLAIN DATA module with no imports beyond
// types: it is loaded in Next middleware, and pulling in the action catalog would
// drag every action's service graph into that bundle.
import type { HiveActionConfirmation, HiveActionRisk, HiveActionSideEffect } from "@/lib/services/hive-actions/types";

export type HiveActionRoutePolicy = {
  route: string;
  actionId: string;
  risk: HiveActionRisk;
  sideEffects: HiveActionSideEffect[];
  readOnly: boolean;
  requiredClaims: string[];
  confirmation: Exclude<HiveActionConfirmation, false> | null;
};

/** Routes served by exactly one hive action, so the route determines the policy. */
export const HIVE_ACTION_ROUTE_POLICIES: HiveActionRoutePolicy[] = [
  {
    "route": "/api/agent-challenges",
    "actionId": "agent-challenge.arena",
    "risk": "medium",
    "sideEffects": [
      "filesystem",
      "write"
    ],
    "readOnly": false,
    "requiredClaims": [
      "filesystem:write",
      "local:write"
    ],
    "confirmation": null
  },
  {
    "route": "/api/app-builder",
    "actionId": "apps.build",
    "risk": "high",
    "sideEffects": [
      "filesystem",
      "network",
      "read",
      "remote-machine",
      "write"
    ],
    "readOnly": false,
    "requiredClaims": [
      "connectors:read",
      "filesystem:write",
      "local:write",
      "machines:write",
      "network:invoke"
    ],
    "confirmation": {
      "reason": "Project creation, dependency installation, file mutation, runtime start/stop, external temporary deployment, paid hosting purchase or renewal, unpublishing, and deletion require explicit confirmation. Read-only actions need no confirmation.",
      "when": "always"
    }
  },
  {
    "route": "/api/brain/memory",
    "actionId": "brain.portability",
    "risk": "medium",
    "sideEffects": [
      "filesystem",
      "read",
      "write"
    ],
    "readOnly": false,
    "requiredClaims": [
      "connectors:read",
      "filesystem:write",
      "local:write"
    ],
    "confirmation": null
  },
  {
    "route": "/api/brain/review",
    "actionId": "brain.review-queue",
    "risk": "medium",
    "sideEffects": [
      "filesystem",
      "write"
    ],
    "readOnly": false,
    "requiredClaims": [
      "filesystem:write",
      "local:write"
    ],
    "confirmation": null
  },
  {
    "route": "/api/clawbank",
    "actionId": "clawbank.status",
    "risk": "low",
    "sideEffects": [
      "network",
      "read"
    ],
    "readOnly": true,
    "requiredClaims": [
      "connectors:read",
      "network:invoke"
    ],
    "confirmation": null
  },
  {
    "route": "/api/clawbank/money",
    "actionId": "clawbank.money-transfer",
    "risk": "critical",
    "sideEffects": [
      "network",
      "payment",
      "wallet"
    ],
    "readOnly": false,
    "requiredClaims": [
      "network:invoke",
      "wallet:spend"
    ],
    "confirmation": {
      "reason": "ClawBank custodial transfers move real funds from the KYC bank account and must pass an explicit confirmation gate.",
      "when": "always"
    }
  },
  {
    "route": "/api/clawbank/trading",
    "actionId": "clawbank.trade",
    "risk": "critical",
    "sideEffects": [
      "network",
      "payment",
      "wallet"
    ],
    "readOnly": false,
    "requiredClaims": [
      "network:invoke",
      "wallet:spend"
    ],
    "confirmation": {
      "reason": "ClawBank swaps trade real funds from the self-custody wallet and must pass an explicit confirmation gate.",
      "when": "always"
    }
  },
  {
    "route": "/api/clawbank/wallet",
    "actionId": "clawbank.send-usdc",
    "risk": "critical",
    "sideEffects": [
      "network",
      "payment",
      "wallet"
    ],
    "readOnly": false,
    "requiredClaims": [
      "network:invoke",
      "wallet:spend"
    ],
    "confirmation": {
      "reason": "ClawBank self-custody USDC sends move real funds on Base and must pass an explicit confirmation gate.",
      "when": "always"
    }
  },
  {
    "route": "/api/companies",
    "actionId": "companies.api-preflight",
    "risk": "low",
    "sideEffects": [
      "write"
    ],
    "readOnly": false,
    "requiredClaims": [
      "local:write"
    ],
    "confirmation": null
  },
  {
    "route": "/api/companies/[id]/api-budget",
    "actionId": "company.api-budget",
    "risk": "high",
    "sideEffects": [
      "network",
      "read",
      "write"
    ],
    "readOnly": false,
    "requiredClaims": [
      "connectors:read",
      "local:write",
      "network:invoke"
    ],
    "confirmation": null
  },
  {
    "route": "/api/company-revenue",
    "actionId": "company.revenue-ledger",
    "risk": "medium",
    "sideEffects": [
      "network",
      "write"
    ],
    "readOnly": false,
    "requiredClaims": [
      "local:write",
      "network:invoke"
    ],
    "confirmation": null
  },
  {
    "route": "/api/computer-interaction",
    "actionId": "computer.interaction",
    "risk": "high",
    "sideEffects": [
      "network",
      "read",
      "write"
    ],
    "readOnly": false,
    "requiredClaims": [
      "connectors:read",
      "local:write",
      "network:invoke"
    ],
    "confirmation": {
      "reason": "Starting or advancing a computer-interaction run can operate a browser or dashboard. The run adds a second, action-level consequence gate before external submissions, sends, purchases, transfers, deletes, uploads, installs, or code execution.",
      "when": "always"
    }
  },
  {
    "route": "/api/context-xray",
    "actionId": "context.xray",
    "risk": "medium",
    "sideEffects": [
      "filesystem",
      "write"
    ],
    "readOnly": false,
    "requiredClaims": [
      "filesystem:write",
      "local:write"
    ],
    "confirmation": null
  },
  {
    "route": "/api/crypto/b20/issuer-proof",
    "actionId": "crypto.b20-issuer-proof",
    "risk": "critical",
    "sideEffects": [
      "network",
      "wallet"
    ],
    "readOnly": false,
    "requiredClaims": [
      "network:invoke",
      "wallet:spend"
    ],
    "confirmation": {
      "reason": "B20 creation deploys a token through the Base B20 factory and must show the deterministic proof before signing.",
      "when": "always"
    }
  },
  {
    "route": "/api/crypto/clear-signing",
    "actionId": "crypto.review-action",
    "risk": "low",
    "sideEffects": [
      "read"
    ],
    "readOnly": true,
    "requiredClaims": [
      "connectors:read"
    ],
    "confirmation": null
  },
  {
    "route": "/api/dashboard/pins",
    "actionId": "dashboard.pins",
    "risk": "medium",
    "sideEffects": [
      "filesystem",
      "write"
    ],
    "readOnly": false,
    "requiredClaims": [
      "filesystem:write",
      "local:write"
    ],
    "confirmation": null
  },
  {
    "route": "/api/fleet/discover",
    "actionId": "fleet.list-machines",
    "risk": "low",
    "sideEffects": [
      "network",
      "read"
    ],
    "readOnly": true,
    "requiredClaims": [
      "connectors:read",
      "network:invoke"
    ],
    "confirmation": null
  },
  {
    "route": "/api/handoff",
    "actionId": "handoff.plan",
    "risk": "low",
    "sideEffects": [
      "network",
      "read"
    ],
    "readOnly": true,
    "requiredClaims": [
      "connectors:read",
      "network:invoke"
    ],
    "confirmation": null
  },
  {
    "route": "/api/hivemindos/models/wallet",
    "actionId": "hivemindos-models.funding-wallet",
    "risk": "medium",
    "sideEffects": [
      "credential",
      "filesystem",
      "write"
    ],
    "readOnly": false,
    "requiredClaims": [
      "credentials:write",
      "filesystem:write",
      "local:write"
    ],
    "confirmation": null
  },
  {
    "route": "/api/integrations/azure/resources",
    "actionId": "integrations.azure-resources",
    "risk": "low",
    "sideEffects": [
      "network",
      "read"
    ],
    "readOnly": true,
    "requiredClaims": [
      "connectors:read",
      "network:invoke"
    ],
    "confirmation": null
  },
  {
    "route": "/api/integrations/calcom",
    "actionId": "integrations.calcom-read",
    "risk": "low",
    "sideEffects": [
      "network",
      "read"
    ],
    "readOnly": true,
    "requiredClaims": [
      "connectors:read",
      "network:invoke"
    ],
    "confirmation": null
  },
  {
    "route": "/api/integrations/medusa",
    "actionId": "integrations.medusa-read",
    "risk": "low",
    "sideEffects": [
      "network",
      "read"
    ],
    "readOnly": true,
    "requiredClaims": [
      "connectors:read",
      "network:invoke"
    ],
    "confirmation": null
  },
  {
    "route": "/api/integrations/robinhood-mcp",
    "actionId": "trading.robinhood-agentic-read",
    "risk": "low",
    "sideEffects": [
      "network",
      "read"
    ],
    "readOnly": true,
    "requiredClaims": [
      "connectors:read",
      "network:invoke"
    ],
    "confirmation": null
  },
  {
    "route": "/api/integrations/shopify",
    "actionId": "integrations.shopify-read",
    "risk": "low",
    "sideEffects": [
      "network",
      "read"
    ],
    "readOnly": true,
    "requiredClaims": [
      "connectors:read",
      "network:invoke"
    ],
    "confirmation": null
  },
  {
    "route": "/api/integrations/slack/send",
    "actionId": "integrations.slack-send",
    "risk": "high",
    "sideEffects": [
      "network",
      "public-message"
    ],
    "readOnly": false,
    "requiredClaims": [
      "messages:publish",
      "network:invoke"
    ],
    "confirmation": {
      "reason": "Posting to Slack publishes a message visible to others as the connected user; the /api/integrations/slack/send route rejects sends without CONFIRM_SLACK_SEND.",
      "when": "always"
    }
  },
  {
    "route": "/api/integrations/x-command",
    "actionId": "integration.x-command-control",
    "risk": "high",
    "sideEffects": [
      "credential",
      "filesystem",
      "network",
      "read",
      "write"
    ],
    "readOnly": false,
    "requiredClaims": [
      "connectors:read",
      "credentials:write",
      "filesystem:write",
      "local:write",
      "network:invoke"
    ],
    "confirmation": null
  },
  {
    "route": "/api/integrations/x-managed",
    "actionId": "integrations.x-managed-api",
    "risk": "high",
    "sideEffects": [
      "network",
      "payment",
      "public-message"
    ],
    "readOnly": false,
    "requiredClaims": [
      "messages:publish",
      "network:invoke",
      "wallet:spend"
    ],
    "confirmation": {
      "reason": "Gateway status, OAuth start, balance, connections, and GET proxy reads do not mutate X, but write (non-GET) proxy calls post or mutate as the connected X account and the route rejects them without CONFIRM_X_API_CALL. All managed calls are paid from hosted HivemindOS credits.",
      "when": "always"
    }
  },
  {
    "route": "/api/integrations/x-mcp",
    "actionId": "integrations.x-mcp-setup",
    "risk": "medium",
    "sideEffects": [
      "credential",
      "filesystem",
      "network",
      "write"
    ],
    "readOnly": false,
    "requiredClaims": [
      "credentials:write",
      "filesystem:write",
      "local:write",
      "network:invoke"
    ],
    "confirmation": null
  },
  {
    "route": "/api/integrations/x-transcript",
    "actionId": "integrations.x-transcript",
    "risk": "low",
    "sideEffects": [
      "network",
      "read"
    ],
    "readOnly": true,
    "requiredClaims": [
      "connectors:read",
      "network:invoke"
    ],
    "confirmation": null
  },
  {
    "route": "/api/managed-cloud-agents",
    "actionId": "cloud.managed-agents",
    "risk": "high",
    "sideEffects": [
      "credential",
      "network",
      "payment",
      "read",
      "remote-machine",
      "wallet",
      "write"
    ],
    "readOnly": false,
    "requiredClaims": [
      "connectors:read",
      "credentials:write",
      "local:write",
      "machines:write",
      "network:invoke",
      "wallet:spend"
    ],
    "confirmation": {
      "reason": "Funding sends Base USDC through the selected governed wallet. The route applies this confirmation only to top-ups; authenticated lifecycle and read operations do not move wallet funds.",
      "when": "unless-auto-policy-allows"
    }
  },
  {
    "route": "/api/nansen/status",
    "actionId": "nansen.intelligence",
    "risk": "low",
    "sideEffects": [
      "network",
      "read"
    ],
    "readOnly": true,
    "requiredClaims": [
      "connectors:read",
      "network:invoke"
    ],
    "confirmation": null
  },
  {
    "route": "/api/ops/investigations",
    "actionId": "ops.investigate-incident",
    "risk": "medium",
    "sideEffects": [
      "filesystem",
      "network",
      "write"
    ],
    "readOnly": false,
    "requiredClaims": [
      "filesystem:write",
      "local:write",
      "network:invoke"
    ],
    "confirmation": null
  },
  {
    "route": "/api/phone/local-tts",
    "actionId": "phone.local-tts",
    "risk": "medium",
    "sideEffects": [
      "network",
      "write"
    ],
    "readOnly": false,
    "requiredClaims": [
      "local:write",
      "network:invoke"
    ],
    "confirmation": null
  },
  {
    "route": "/api/quant-research",
    "actionId": "research.quant-swarm",
    "risk": "medium",
    "sideEffects": [
      "filesystem",
      "write"
    ],
    "readOnly": false,
    "requiredClaims": [
      "filesystem:write",
      "local:write"
    ],
    "confirmation": null
  },
  {
    "route": "/api/queen-bee",
    "actionId": "queen-bee.orchestration",
    "risk": "medium",
    "sideEffects": [
      "filesystem",
      "write"
    ],
    "readOnly": false,
    "requiredClaims": [
      "filesystem:write",
      "local:write"
    ],
    "confirmation": null
  },
  {
    "route": "/api/skills/autoresearch",
    "actionId": "skills.autoresearch",
    "risk": "medium",
    "sideEffects": [
      "filesystem",
      "read",
      "write"
    ],
    "readOnly": false,
    "requiredClaims": [
      "connectors:read",
      "filesystem:write",
      "local:write"
    ],
    "confirmation": null
  },
  {
    "route": "/api/trading",
    "actionId": "wallet.stock-trade",
    "risk": "critical",
    "sideEffects": [
      "network",
      "payment",
      "wallet"
    ],
    "readOnly": false,
    "requiredClaims": [
      "network:invoke",
      "wallet:spend"
    ],
    "confirmation": {
      "reason": "Stock trades can place real brokerage or tokenized-asset orders and must pass venue policy and explicit side-specific confirmation.",
      "when": "always"
    }
  },
  {
    "route": "/api/trading/bankr-copy",
    "actionId": "trading.bankr-copy",
    "risk": "critical",
    "sideEffects": [
      "credential",
      "network",
      "payment",
      "wallet"
    ],
    "readOnly": false,
    "requiredClaims": [
      "credentials:write",
      "network:invoke",
      "wallet:spend"
    ],
    "confirmation": {
      "reason": "Subscribing settles the subscription price over x402 from the payment wallet, and funding transfers real USDC into the Bankr trading wallet — funding requires the exact FUND_BANKR_COPY_WALLET confirmation, and switching to live mode requires an explicit risk acknowledgement.",
      "when": "always"
    }
  },
  {
    "route": "/api/trading/control",
    "actionId": "trading.control-plane",
    "risk": "high",
    "sideEffects": [
      "filesystem",
      "network",
      "read",
      "write"
    ],
    "readOnly": false,
    "requiredClaims": [
      "connectors:read",
      "filesystem:write",
      "local:write",
      "network:invoke"
    ],
    "confirmation": null
  },
  {
    "route": "/api/trading/copy-trade",
    "actionId": "trading.copy-trade-config",
    "risk": "high",
    "sideEffects": [
      "filesystem",
      "write"
    ],
    "readOnly": false,
    "requiredClaims": [
      "filesystem:write",
      "local:write"
    ],
    "confirmation": null
  },
  {
    "route": "/api/trading/hyperliquid",
    "actionId": "wallet.hyperliquid-trade",
    "risk": "critical",
    "sideEffects": [
      "network",
      "payment",
      "wallet"
    ],
    "readOnly": false,
    "requiredClaims": [
      "network:invoke",
      "wallet:spend"
    ],
    "confirmation": {
      "reason": "Hyperliquid orders, account changes, transfers, withdrawals, cancels, TWAPs, and builder approvals can change real exchange state or funds and require action-specific confirmation.",
      "when": "always"
    }
  },
  {
    "route": "/api/trading/liquidity-range",
    "actionId": "trading.liquidity-range-manager",
    "risk": "medium",
    "sideEffects": [
      "filesystem",
      "network",
      "read",
      "write"
    ],
    "readOnly": false,
    "requiredClaims": [
      "connectors:read",
      "filesystem:write",
      "local:write",
      "network:invoke"
    ],
    "confirmation": null
  },
  {
    "route": "/api/trading/market",
    "actionId": "trading.market-data",
    "risk": "low",
    "sideEffects": [
      "network",
      "read"
    ],
    "readOnly": true,
    "requiredClaims": [
      "connectors:read",
      "network:invoke"
    ],
    "confirmation": null
  },
  {
    "route": "/api/trading/plume",
    "actionId": "wallet.plume-options",
    "risk": "critical",
    "sideEffects": [
      "network",
      "payment",
      "wallet"
    ],
    "readOnly": false,
    "requiredClaims": [
      "network:invoke",
      "wallet:spend"
    ],
    "confirmation": {
      "reason": "Option actions approve or move testnet assets and must pass a server-derived review, wallet governance, jurisdiction attestation, simulation, and exact action-specific confirmation.",
      "when": "always"
    }
  },
  {
    "route": "/api/trading/practice-book",
    "actionId": "wallet.crypto-practice-book",
    "risk": "critical",
    "sideEffects": [
      "network",
      "payment",
      "wallet"
    ],
    "readOnly": false,
    "requiredClaims": [
      "network:invoke",
      "wallet:spend"
    ],
    "confirmation": {
      "reason": "Reading and planning are safe, but the execute-hyperliquid-replay action can place Hyperliquid orders and must always pass an explicit replay confirmation plus wallet governance.",
      "when": "always"
    }
  },
  {
    "route": "/api/trading/prediction",
    "actionId": "trading.prediction-markets-research",
    "risk": "low",
    "sideEffects": [
      "network",
      "read"
    ],
    "readOnly": true,
    "requiredClaims": [
      "connectors:read",
      "network:invoke"
    ],
    "confirmation": null
  },
  {
    "route": "/api/trading/swap",
    "actionId": "wallet.dex-swap",
    "risk": "critical",
    "sideEffects": [
      "network",
      "payment",
      "wallet"
    ],
    "readOnly": false,
    "requiredClaims": [
      "network:invoke",
      "wallet:spend"
    ],
    "confirmation": {
      "reason": "DEX swaps trade assets and must pass spend policy, quote review, slippage checks, and explicit confirmation.",
      "when": "always"
    }
  },
  {
    "route": "/api/visual-artifacts",
    "actionId": "visual.artifacts",
    "risk": "medium",
    "sideEffects": [
      "filesystem",
      "write"
    ],
    "readOnly": false,
    "requiredClaims": [
      "filesystem:write",
      "local:write"
    ],
    "confirmation": null
  },
  {
    "route": "/api/wallet/send",
    "actionId": "wallet.send-usdc",
    "risk": "critical",
    "sideEffects": [
      "network",
      "payment",
      "wallet"
    ],
    "readOnly": false,
    "requiredClaims": [
      "network:invoke",
      "wallet:spend"
    ],
    "confirmation": {
      "reason": "Stablecoin sends move funds and must pass the wallet route's spend policy and explicit confirmation gate.",
      "when": "always"
    }
  },
  {
    "route": "/api/wallet/x402",
    "actionId": "wallet.x402-fetch",
    "risk": "critical",
    "sideEffects": [
      "network",
      "payment",
      "wallet"
    ],
    "readOnly": false,
    "requiredClaims": [
      "network:invoke",
      "wallet:spend"
    ],
    "confirmation": {
      "reason": "x402 fetches settle real USDC when the endpoint returns a payment quote. Personal user wallets never auto-pay and always need the explicit PAY_X402 confirmation; agent wallets must pass their governed spend policy first.",
      "when": "unless-auto-policy-allows"
    }
  },
  {
    "route": "/api/web-research/crawl",
    "actionId": "web.crawl",
    "risk": "low",
    "sideEffects": [
      "network",
      "read"
    ],
    "readOnly": true,
    "requiredClaims": [
      "connectors:read",
      "network:invoke"
    ],
    "confirmation": null
  },
  {
    "route": "/api/web-research/fetch",
    "actionId": "web.fetch",
    "risk": "low",
    "sideEffects": [
      "network",
      "read"
    ],
    "readOnly": true,
    "requiredClaims": [
      "connectors:read",
      "network:invoke"
    ],
    "confirmation": null
  },
  {
    "route": "/api/web-research/screenshot",
    "actionId": "web.screenshot",
    "risk": "low",
    "sideEffects": [
      "network",
      "read"
    ],
    "readOnly": true,
    "requiredClaims": [
      "connectors:read",
      "network:invoke"
    ],
    "confirmation": null
  },
  {
    "route": "/api/web-research/search",
    "actionId": "web.search",
    "risk": "low",
    "sideEffects": [
      "network",
      "read"
    ],
    "readOnly": true,
    "requiredClaims": [
      "connectors:read",
      "network:invoke"
    ],
    "confirmation": null
  },
  {
    "route": "/api/work-events",
    "actionId": "work-event.fanout",
    "risk": "medium",
    "sideEffects": [
      "filesystem",
      "write"
    ],
    "readOnly": false,
    "requiredClaims": [
      "filesystem:write",
      "local:write"
    ],
    "confirmation": null
  }
];

/**
 * Routes served by SEVERAL actions at differing risk. The action is chosen by the
 * request body, which middleware cannot read, so these are intentionally not
 * enforced at the proxy — they need enforcement inside the route handler, where
 * the action is known. Listed rather than silently dropped so the gap is visible.
 */
export const AMBIGUOUS_HIVE_ACTION_ROUTES: Array<{ route: string; actionIds: string[] }> = [
  {
    "route": "/api/apify",
    "actionIds": [
      "apify.fund",
      "apify.run-actor",
      "apify.search-actors",
      "apify.x402-status"
    ]
  },
  {
    "route": "/api/beeline/actions",
    "actionIds": [
      "beeline.browser-use",
      "beeline.open-browser",
      "beeline.profiles"
    ]
  },
  {
    "route": "/api/beeline/broker",
    "actionIds": [
      "beeline.calendar-create",
      "beeline.calendar-list",
      "beeline.connections",
      "beeline.mcp-call",
      "beeline.mcp-read"
    ]
  },
  {
    "route": "/api/beeline/local-credentials",
    "actionIds": [
      "beeline.local-credential-use",
      "beeline.local-credentials"
    ]
  },
  {
    "route": "/api/brain/knowledge",
    "actionIds": [
      "brain.get-node",
      "brain.graph-overview",
      "brain.search-knowledge",
      "brain.shared-contract"
    ]
  },
  {
    "route": "/api/clawbank/run",
    "actionIds": [
      "clawbank.call",
      "clawbank.list-tools",
      "clawbank.read"
    ]
  },
  {
    "route": "/api/code-intelligence",
    "actionIds": [
      "code.detect-changes",
      "code.get-architecture",
      "code.get-snippet",
      "code.index-repository",
      "code.search-graph",
      "code.trace-path"
    ]
  },
  {
    "route": "/api/crypto/capabilities",
    "actionIds": [
      "crypto.capabilities",
      "crypto.prepare-action"
    ]
  },
  {
    "route": "/api/hivemind-office",
    "actionIds": [
      "hivemind-office.apply-update",
      "hivemind-office.inspect-document",
      "hivemind-office.open-document",
      "hivemind-office.prepare-update",
      "hivemind-office.status"
    ]
  },
  {
    "route": "/api/hivemindos-machines/azure",
    "actionIds": [
      "machines.hivemindos-catalog",
      "machines.hivemindos-deploy"
    ]
  },
  {
    "route": "/api/hivemindos/media",
    "actionIds": [
      "hosted-media.catalog",
      "hosted-media.generate",
      "hosted-media.read"
    ]
  },
  {
    "route": "/api/integrations/google/slides",
    "actionIds": [
      "integrations.google-slides-edit",
      "integrations.google-slides-read"
    ]
  },
  {
    "route": "/api/integrations/monid",
    "actionIds": [
      "integrations.monid-read",
      "integrations.monid-run"
    ]
  },
  {
    "route": "/api/kanban",
    "actionIds": [
      "human-approval.request",
      "work-board.lifecycle"
    ]
  },
  {
    "route": "/api/socials/queue",
    "actionIds": [
      "socials.queue-by-account-policy",
      "socials.queue-suggestion"
    ]
  }
];

const POLICY_BY_ROUTE = new Map(HIVE_ACTION_ROUTE_POLICIES.map((policy) => [policy.route, policy]));

export function hiveActionRoutePolicy(pathname: string): HiveActionRoutePolicy | null {
  return POLICY_BY_ROUTE.get(pathname) ?? null;
}
