/**
 * One honest sentence telling the brain which LLM serves this turn. An LLM has
 * no innate knowledge of its own model id; callers pass the model they are
 * actually about to invoke, so the note is exact per lane.
 */
export function queenModelTransparencyNote(
  model: string,
  providerLabel: string,
  opts?: { relayTool?: boolean },
): string {
  const id = model.trim();
  if (!id) return "";
  return [
    `Model transparency: this reply is generated by the LLM "${id}" via ${providerLabel.trim() || "its provider"}.`,
    "When the user asks which model, LLM, or brain you are or run on, state this plainly - never claim you cannot know.",
    opts?.relayTool
      ? "Requests you relay through ask_hivemind_agent are answered by that hive agent's own configured model, not yours - say so when the distinction matters."
      : "",
  ]
    .filter(Boolean)
    .join(" ");
}
