"use client";

/* Intelligence.tsx — the run-intelligence / analysis panel. Surfaces what moved
   the swarm, which agents would flip the call, and what would change it (or, for
   trading runs, the risk read). Reads from useSimData().intelFor(run). */

import React from "react";
import { Icon, type IconName } from "./icons";
import { type Run, type SwingAgent } from "./sim-data";
import { useSimData } from "./sim-context";

function IntelCol<T>({ icon, label, tone, items, render }: {
  icon: IconName; label: string; tone: string; items: T[]; render?: (it: T) => React.ReactNode;
}) {
  return (
    <div className="intel-col">
      <div style={{ display: "flex", alignItems: "center", gap: 7, marginBottom: 10 }}>
        <Icon name={icon} size={13} color={tone} /><span className="sv-eyebrow" style={{ color: "var(--fg-3)" }}>{label}</span>
      </div>
      <div>{items.map((it, i) => (
        <div key={i} className="intel-li">
          <span style={{ marginTop: 5, width: 5, height: 5, borderRadius: 99, background: tone, flex: "0 0 auto" }} />
          <span>{render ? render(it) : (it as React.ReactNode)}</span>
        </div>
      ))}</div>
    </div>
  );
}

export function Intelligence({ run }: { run: Run }) {
  const intel = useSimData().intelFor(run);
  if (!intel) return null;
  const isRisk = intel.kind === "risk";
  return (
    <div style={{ background: "var(--panel)", border: "1px solid var(--line)", borderRadius: "var(--radius)", padding: "16px 18px" }}>
      <div style={{ display: "flex", alignItems: "center", gap: 8, marginBottom: 12 }}>
        <Icon name="sparkles" size={15} color="var(--honey)" />
        <span className="sv-eyebrow" style={{ color: "var(--honey)" }}>Run intelligence</span>
        <span className="sv-mono" style={{ fontSize: 10, color: "var(--fg-4)" }}>· generated by the report agent</span>
      </div>
      <p style={{ margin: "0 0 16px", fontSize: 14, color: "var(--fg)", lineHeight: 1.5, fontWeight: 500, textWrap: "pretty" }}>{intel.read}</p>
      <div style={{ display: "grid", gridTemplateColumns: "repeat(3, 1fr)", gap: 12 }}>
        <IntelCol<string> icon={isRisk ? "activity" : "trade"} label={isRisk ? "What's working" : "What moved the swarm"} tone="var(--live)" items={intel.drivers} />
        <IntelCol<SwingAgent> icon="bot" label="Swing agents" tone="var(--honey)" items={intel.swing} render={(s) => <><strong style={{ color: "var(--fg)", fontWeight: 600 }}>{s.name}</strong> — {s.note}</>} />
        <IntelCol<string> icon={isRisk ? "warn" : "branch"} label={isRisk ? "Risk triggers" : "What would change the call"} tone={isRisk ? "var(--danger)" : "var(--fg-2)"} items={intel.flipIf} />
      </div>
    </div>
  );
}
