[package]
name = "hivemindos-biometric-native"
version = "0.1.0"
edition = "2021"

[lib]
name = "hivemindos_biometric_native"

[target.'cfg(target_os = "macos")'.dependencies]
block2 = "0.6"
objc2 = "0.6"
objc2-foundation = { version = "0.3", default-features = false, features = [
  "std",
  "NSError",
  "NSString",
] }
objc2-local-authentication = { version = "0.3.2", default-features = false, features = [
  "std",
  "block2",
  "LAContext",
  "LABiometryType",
  "LAPublicDefines",
] }
