#!/usr/bin/env python3
"""Alias for hive-env-remove."""
from __future__ import annotations

import os
import pathlib
import sys

SCRIPT_PATH = pathlib.Path(__file__).resolve()
TARGET = SCRIPT_PATH.with_name("hive-env-remove")

os.execv(sys.executable, [sys.executable, str(TARGET), *sys.argv[1:]])
