#!/usr/bin/env bash
set -euo pipefail

PORT="${AGENT_TELEMETRY_PORT:-8787}"
REQUESTED_PORT="$PORT"
TAILNET_COLLECTOR_PORT="${HIVE_TAILNET_COLLECTOR_PORT:-8787}"
LINK_TAILNET_PORT="${HIVE_LINK_TAILNET_PORT:-8787}"
HERMES_API_HOST="${AGENT_TELEMETRY_HERMES_API_HOST:-127.0.0.1}"
HERMES_API_PORT="${AGENT_TELEMETRY_HERMES_API_PORT:-8642}"
HERMES_RESTART_MODE="${AGENT_TELEMETRY_HERMES_RESTART:-now}"
# The Hermes API server (dashboard <-> agent chat bridge) refuses to start
# without API_SERVER_KEY; resolved/generated by configure_hermes_api_server and
# propagated to the collector service env below.
HERMES_API_KEY_VALUE=""
HERMES_API_KEY_GENERATED=0
HERMES_BRIDGE_RESTART_MARKER="$HOME/.hivemindos/hermes-api-bridge.restarted"
NETWORK_MANAGED_BY_SETUP="${HIVE_SETUP_NETWORK_MANAGED:-false}"
SETUP_TAILNET_SYNC_ENABLED="${HIVE_SETUP_TAILNET_SYNC_ENABLED:-false}"
LINK_ENABLED="${HIVE_LINK_ENABLED:-false}"
COLLECTOR_ONLY="${HIVE_COLLECTOR_ONLY:-}"
APP_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
# shellcheck source=scripts/macos-background-helpers.sh
. "$APP_DIR/scripts/macos-background-helpers.sh"
COLLECTOR="$APP_DIR/scripts/agent-telemetry-collector.mjs"
SYNCTHING_RUNNER="$APP_DIR/scripts/run-syncthing.sh"
LINK_BIN="${HIVE_LINK_BIN:-$APP_DIR/bin/hivemind-linkd}"
LINK_LABEL="${HIVE_LINK_LABEL:-com.hivemindos.linkd.agent}"
LINK_LEGACY_LABEL="com.hivemindos.linkd"
LINK_CONTROL="${HIVE_LINK_CONTROL:-127.0.0.1:${HIVE_LINK_CONTROL_PORT:-8788}}"
LINK_STATE_DIR="${HIVE_LINK_STATE_DIR:-$HOME/.hivemindos/link/default}"
if [[ -n "${HIVE_LINK_LOG_FILE:-}" ]]; then
  LINK_LOG_FILE="$HIVE_LINK_LOG_FILE"
elif [[ "$(uname -s)" == "Darwin" ]]; then
  LINK_LOG_FILE="$HOME/Library/Logs/hivemindos-linkd.err.log"
else
  LINK_LOG_FILE="$HOME/.hivemindos/link/hivemind-linkd.err.log"
fi
LINK_LOG_MAX_BYTES="${HIVE_LINK_LOG_MAX_BYTES:-2097152}"
LINK_TAILSCALE_DEBUG_LOGS="${HIVE_LINK_TAILSCALE_DEBUG_LOGS:-false}"
LINK_DISABLE_PORTLIST="${HIVE_LINK_DISABLE_PORTLIST:-true}"
LINK_RUN_WEB_CLIENT="${HIVE_LINK_RUN_WEB_CLIENT:-false}"
LINK_EPHEMERAL="${HIVE_LINK_EPHEMERAL:-false}"
LINK_STATUS_TIMEOUT="${HIVE_LINK_STATUS_TIMEOUT:-3s}"
LINK_CONTROL_STATUS_URL="http://$LINK_CONTROL/status"
LINK_CONTROL_HEALTH_URL="http://$LINK_CONTROL/health"
SYSTEM_TAILNET_SERVE_ACTIVE="false"
NODE_BIN="$(command -v node)"
MACOS_BACKGROUND_HELPER_SOURCE="$APP_DIR/scripts/hivemindos-background-helper.c"
MACOS_COLLECTOR_HELPER_NAME="HivemindOS Collector"
MACOS_COLLECTOR_HELPER_ID="com.hivemindos.collector-helper"
MACOS_COLLECTOR_HELPER_HOME="$HOME/.hivemindos/bin/$MACOS_COLLECTOR_HELPER_NAME"
MACOS_SYNC_HELPER_NAME="HivemindOS Sync"
MACOS_SYNC_HELPER_ID="com.hivemindos.sync-helper"
MACOS_SYNC_HELPER_HOME="$HOME/.hivemindos/bin/$MACOS_SYNC_HELPER_NAME"

if [[ -z "${HIVE_LINK_CONTROL:-}" && -f "$HOME/.hivemindos/collector.env" ]]; then
  EXISTING_LINK_CONTROL="$(awk -F= '$1=="HIVE_LINK_CONTROL"{print substr($0, index($0, "=") + 1)}' "$HOME/.hivemindos/collector.env" | tail -1)"
  if [[ -n "$EXISTING_LINK_CONTROL" ]]; then
    LINK_CONTROL="${EXISTING_LINK_CONTROL%\"}"
    LINK_CONTROL="${LINK_CONTROL#\"}"
    LINK_CONTROL="${LINK_CONTROL%\'}"
    LINK_CONTROL="${LINK_CONTROL#\'}"
  fi
fi
if [[ -z "${HIVE_LINK_ENABLED:-}" && -f "$HOME/.hivemindos/collector.env" ]] && grep -q '^HIVE_LINK_LABEL=' "$HOME/.hivemindos/collector.env" 2>/dev/null; then
  LINK_ENABLED="true"
fi
# Collector-only machines skip the dashboard build/install entirely; the mode is
# sticky via collector.env so plain installer reruns keep it.
if [[ -z "$COLLECTOR_ONLY" && -f "$HOME/.hivemindos/collector.env" ]]; then
  COLLECTOR_ONLY="$(awk -F= '$1=="HIVE_COLLECTOR_ONLY"{print substr($0, index($0, "=") + 1)}' "$HOME/.hivemindos/collector.env" | tail -1)"
fi
case "$COLLECTOR_ONLY" in
  1|true|TRUE|yes|YES) COLLECTOR_ONLY="true" ;;
  *) COLLECTOR_ONLY="false" ;;
esac
LINK_CONTROL_STATUS_URL="http://$LINK_CONTROL/status"
LINK_CONTROL_HEALTH_URL="http://$LINK_CONTROL/health"

if [[ ! -f "$COLLECTOR" ]]; then
  echo "Missing collector: $COLLECTOR" >&2
  exit 1
fi

# The collector imports bonjour-service; make sure it resolves even when the full
# workspace install never ran (collector-only machines). No-op otherwise.
"$APP_DIR/scripts/ensure-collector-deps.sh"

resolve_macos_collector_program_arguments() {
  if [[ "$(uname -s)" != "Darwin" ]]; then
    printf "<string>%s</string>\n    <string>%s</string>" "$NODE_BIN" "$COLLECTOR"
    return 0
  fi

  if [[ -n "${HIVE_COLLECTOR_HELPER_BIN:-}" && -x "${HIVE_COLLECTOR_HELPER_BIN:-}" ]]; then
    printf "<string>%s</string>\n    <string>%s</string>\n    <string>%s</string>" "$HIVE_COLLECTOR_HELPER_BIN" "$NODE_BIN" "$COLLECTOR"
    return 0
  fi

  local helper_path
  if helper_path="$(hivemindos_resolve_background_helper \
    "$MACOS_COLLECTOR_HELPER_NAME" \
    "$MACOS_COLLECTOR_HELPER_ID" \
    "$MACOS_BACKGROUND_HELPER_SOURCE" \
    "$MACOS_COLLECTOR_HELPER_HOME" \
    "$APP_DIR/src-tauri/resources/hivemindos-collector-helper/$MACOS_COLLECTOR_HELPER_NAME" \
    "$APP_DIR/resources/hivemindos-collector-helper/$MACOS_COLLECTOR_HELPER_NAME")"; then
    printf "<string>%s</string>\n    <string>%s</string>\n    <string>%s</string>" "$helper_path" "$NODE_BIN" "$COLLECTOR"
    return 0
  fi

  echo "Warning: could not build HivemindOS Collector helper; falling back to raw Node in the LaunchAgent." >&2
  printf "<string>%s</string>\n    <string>%s</string>" "$NODE_BIN" "$COLLECTOR"
}

resolve_macos_sync_helper() {
  hivemindos_resolve_background_helper \
    "$MACOS_SYNC_HELPER_NAME" \
    "$MACOS_SYNC_HELPER_ID" \
    "$MACOS_BACKGROUND_HELPER_SOURCE" \
    "$MACOS_SYNC_HELPER_HOME" \
    "$APP_DIR/src-tauri/resources/hivemindos-sync-helper/$MACOS_SYNC_HELPER_NAME" \
    "$APP_DIR/resources/hivemindos-sync-helper/$MACOS_SYNC_HELPER_NAME"
}

run_privileged() {
  if [[ "$(id -u)" == "0" ]]; then
    "$@"
  elif command -v sudo >/dev/null 2>&1; then
    sudo "$@"
  else
    return 127
  fi
}

apt_install() {
  run_privileged apt-get update
  DEBIAN_FRONTEND=noninteractive run_privileged apt-get install -y "$@"
}

dnf_install() {
  run_privileged dnf install -y "$@"
}

yum_install() {
  run_privileged yum install -y "$@"
}

install_rsync_if_missing() {
  if command -v rsync >/dev/null 2>&1; then
    return
  fi
  echo "rsync is missing; trying to install it for Hivemind Sync vault repair"
  if [[ "$(uname -s)" == "Darwin" ]] && command -v brew >/dev/null 2>&1; then
    brew install rsync
  elif command -v apt-get >/dev/null 2>&1; then
    apt_install rsync
  elif command -v dnf >/dev/null 2>&1; then
    dnf_install rsync
  elif command -v yum >/dev/null 2>&1; then
    yum_install rsync
  else
    echo "Install rsync to use Hivemind Sync vault repair." >&2
  fi
}

install_syncthing_if_missing() {
  if command -v syncthing >/dev/null 2>&1; then
    return
  fi
  echo "Syncthing is missing; trying to install it for Hivemind Sync folder sync"
  if [[ "$(uname -s)" == "Darwin" ]] && command -v brew >/dev/null 2>&1; then
    brew install syncthing
  elif command -v apt-get >/dev/null 2>&1; then
    apt_install syncthing
  elif command -v dnf >/dev/null 2>&1; then
    dnf_install syncthing
  elif command -v yum >/dev/null 2>&1; then
    yum_install syncthing
  else
    echo "Install Syncthing to use Hivemind Sync folder sync." >&2
  fi
}

install_go_if_missing() {
  if command -v go >/dev/null 2>&1; then
    return 0
  fi
  if [[ "$(uname -s)" == "Darwin" ]] && { command -v brew >/dev/null 2>&1 || load_homebrew_shellenv; }; then
    if ! prompt_yes_no "Go is missing. Install Go so Hivemind Link can build its embedded Tailscale sidecar?" "yes"; then
      return 1
    fi
    brew install go
  elif command -v apt-get >/dev/null 2>&1; then
    apt_install golang-go
  elif command -v dnf >/dev/null 2>&1; then
    dnf_install golang
  elif command -v yum >/dev/null 2>&1; then
    yum_install golang
  else
    echo "Install Go, then rerun ./scripts/install-telemetry-collector.sh with HIVE_LINK_ENABLED=true." >&2
    return 1
  fi
  command -v go >/dev/null 2>&1
}

build_hivemind_linkd_if_enabled() {
  [[ "$LINK_ENABLED" == "true" ]] || return 1
  if [[ -x "$LINK_BIN" ]]; then
    if [[ "$LINK_BIN" -nt "$APP_DIR/cmd/hivemind-linkd/main.go" && "$LINK_BIN" -nt "$APP_DIR/go.mod" && "$LINK_BIN" -nt "$APP_DIR/go.sum" ]]; then
      hivemindos_sign_macos_binary "$LINK_BIN" "com.hivemindos.linkd"
      return 0
    fi
  fi
  install_go_if_missing || return 1
  "$APP_DIR/scripts/build-hivemind-linkd.sh" >/dev/null
  [[ -x "$LINK_BIN" ]]
}

load_homebrew_shellenv() {
  local brew_bin=""
  if command -v brew >/dev/null 2>&1; then
    brew_bin="$(command -v brew)"
  elif [[ -x /opt/homebrew/bin/brew ]]; then
    brew_bin="/opt/homebrew/bin/brew"
  elif [[ -x /usr/local/bin/brew ]]; then
    brew_bin="/usr/local/bin/brew"
  fi
  if [[ -n "$brew_bin" ]]; then
    eval "$("$brew_bin" shellenv)"
    return 0
  fi
  return 1
}

homebrew_tailscale_cli() {
  local prefix candidate
  for candidate in /opt/homebrew/opt/tailscale/bin/tailscale /opt/homebrew/bin/tailscale /usr/local/opt/tailscale/bin/tailscale /usr/local/bin/tailscale; do
    [[ -x "$candidate" ]] && printf "%s\n" "$candidate" && return
  done
  if command -v brew >/dev/null 2>&1; then
    prefix="$(brew --prefix tailscale 2>/dev/null || true)"
    [[ -n "$prefix" && -x "$prefix/bin/tailscale" ]] && printf "%s\n" "$prefix/bin/tailscale"
  fi
}

homebrew_tailscale_formula_installed() {
  command -v brew >/dev/null 2>&1 && brew list --formula tailscale >/dev/null 2>&1
}

tailscale_cli_candidates() {
  if [[ -n "${HIVE_TAILSCALE_CLI:-}" && -x "${HIVE_TAILSCALE_CLI:-}" ]]; then
    printf "%s\n" "$HIVE_TAILSCALE_CLI"
  fi
  homebrew_tailscale_cli
  command -v tailscale 2>/dev/null || true
}

tailscale_cli_socket_arg() {
  local cli="$1"
  [[ "$(uname -s)" == "Darwin" ]] || return 1
  case "$cli" in
    /opt/homebrew/*|/usr/local/*) ;;
    *) return 1 ;;
  esac
  if [[ -S /var/run/tailscaled.socket ]]; then
    printf "%s\n" "--socket=/var/run/tailscaled.socket"
    return 0
  fi
  return 1
}

run_tailscale_cli() {
  local cli="$1"
  shift
  local socket_arg
  socket_arg="$(tailscale_cli_socket_arg "$cli" || true)"
  if [[ -n "$socket_arg" ]]; then
    "$cli" "$socket_arg" "$@"
  else
    "$cli" "$@"
  fi
}

run_tailscale_cli_sudo() {
  local cli="$1"
  shift
  local socket_arg
  socket_arg="$(tailscale_cli_socket_arg "$cli" || true)"
  if [[ -n "$socket_arg" ]]; then
    sudo "$cli" "$socket_arg" "$@"
  else
    sudo "$cli" "$@"
  fi
}

run_tailscale_cli_sudo_noninteractive() {
  local cli="$1"
  shift
  local socket_arg
  socket_arg="$(tailscale_cli_socket_arg "$cli" || true)"
  if [[ -n "$socket_arg" ]]; then
    sudo -n "$cli" "$socket_arg" "$@"
  else
    sudo -n "$cli" "$@"
  fi
}

tailscale_prefs_has() {
  local pattern="$1"
  local cli
  if [[ -z "${HIVE_TAILSCALE_CLI:-}" ]] && command -v tailscale >/dev/null 2>&1 && tailscale debug prefs 2>/dev/null | grep -q "$pattern"; then
    return 0
  fi
  while IFS= read -r cli; do
    [[ -n "$cli" ]] || continue
    run_tailscale_cli "$cli" debug prefs 2>/dev/null | grep -q "$pattern" && return 0
    run_tailscale_cli_sudo_noninteractive "$cli" debug prefs 2>/dev/null | grep -q "$pattern" && return 0
  done < <(tailscale_cli_candidates | awk '!seen[$0]++')
  return 1
}

tailscale_up_retry_args_from_error() {
  awk '
    /^[[:space:]]*tailscale up[[:space:]]/ {
      sub(/^[[:space:]]*tailscale up[[:space:]]*/, "");
      print;
      exit;
    }
  '
}

tailscale_auth_url_from_output() {
  awk '/https:\/\/login\.tailscale\.com\/a\// { print $1; exit }'
}

wait_for_tailscale_running() {
  local formula_cli="$1"
  local seconds="${2:-180}"
  local elapsed=0
  while (( elapsed < seconds )); do
    if run_tailscale_cli_sudo "$formula_cli" status >/dev/null 2>&1; then
      return 0
    fi
    sleep 3
    elapsed=$((elapsed + 3))
  done
  return 1
}

wait_for_tailscale_auth_confirmation() {
  if [[ ! -t 0 || ! -t 1 ]]; then
    return 0
  fi
  printf "Press Enter once you've logged in at the above URL. "
  read -r _ || true
}

tailscale_status_connected() {
  local cli
  if [[ -z "${HIVE_TAILSCALE_CLI:-}" ]] && command -v tailscale >/dev/null 2>&1 && tailscale status >/dev/null 2>&1; then
    return 0
  fi
  while IFS= read -r cli; do
    [[ -n "$cli" ]] || continue
    run_tailscale_cli "$cli" status >/dev/null 2>&1 && return 0
    run_tailscale_cli_sudo_noninteractive "$cli" status >/dev/null 2>&1 && return 0
  done < <(tailscale_cli_candidates | awk '!seen[$0]++')
  return 1
}

connect_homebrew_tailscaled() {
  local formula_cli="$1"
  local output retry_args auth_url
  output="$(run_with_timeout 45 run_tailscale_cli_sudo "$formula_cli" up --timeout=30s 2>&1)" && return 0
  retry_args="$(printf "%s\n" "$output" | tailscale_up_retry_args_from_error)"
  if [[ -n "$retry_args" ]]; then
    # shellcheck disable=SC2086
    output="$(run_with_timeout 45 run_tailscale_cli_sudo "$formula_cli" up $retry_args 2>&1)" && return 0
  fi
  auth_url="$(printf "%s\n" "$output" | tailscale_auth_url_from_output)"
  if [[ -n "$auth_url" ]]; then
    echo "Tailscale sign-in required."
    printf "Open this URL on any device to sign in:\n  %s\n" "$auth_url"
    wait_for_tailscale_auth_confirmation
    if wait_for_tailscale_running "$formula_cli" 180; then
      return 0
    fi
  fi
  printf "%s\n" "$output" >&2
  return 1
}

install_tailscale_if_missing() {
  if command -v tailscale >/dev/null 2>&1 || [[ -n "$(tailscale_cli_candidates | head -1)" ]]; then
    return 0
  fi
  if ! prompt_yes_no "Tailscale is missing. Install it for Fleet discovery and shared-memory sync?" "yes"; then
    return 1
  fi
  if [[ "$(uname -s)" == "Darwin" ]]; then
    setup_homebrew_tailscaled_for_fleet
    return
  elif command -v apt-get >/dev/null 2>&1 && command -v curl >/dev/null 2>&1; then
    curl -fsSL https://tailscale.com/install.sh | sh
  elif command -v dnf >/dev/null 2>&1; then
    dnf_install tailscale
    run_privileged systemctl enable --now tailscaled || true
  elif command -v yum >/dev/null 2>&1; then
    yum_install tailscale
    run_privileged systemctl enable --now tailscaled || true
  else
    echo "No automatic Tailscale installer found for this OS." >&2
    return 1
  fi
}

ensure_tailscale_connected() {
  local cli
  if tailscale_status_connected; then
    return 0
  fi
  install_tailscale_if_missing || return 1
  if tailscale_status_connected; then
    return 0
  fi
  if [[ "$(uname -s)" == "Darwin" ]]; then
    setup_homebrew_tailscaled_for_fleet || true
    tailscale_status_connected && return 0
  fi
  cli="$(tailscale_cli_candidates | awk '!seen[$0]++ { print; exit }')"
  if [[ -z "$cli" ]]; then
    return 1
  fi
  if ! prompt_yes_no "Tailscale is installed but not logged in. Start Tailscale login now and wait for it to finish?" "yes"; then
    return 1
  fi
  connect_homebrew_tailscaled "$cli"
}

quit_macos_tailscale_gui() {
  [[ "$(uname -s)" == "Darwin" ]] || return 0
  osascript -e 'quit app "Tailscale"' >/dev/null 2>&1 || true
  sleep 2
}

setup_homebrew_tailscaled_for_fleet() {
  [[ "$(uname -s)" == "Darwin" ]] || return 1
  [[ -t 0 && -t 1 ]] || return 1
  [[ "${HIVE_TAILSCALED_SWITCH_ATTEMPTED:-false}" != "true" ]] || return 1
  export HIVE_TAILSCALED_SWITCH_ATTEMPTED="true"
  load_homebrew_shellenv || return 1
  if ! prompt_yes_no "Switch this Mac to the Homebrew Tailscale daemon so Fleet can manage Tailnet reachability reliably?" "yes"; then
    echo "Leaving the current Tailscale backend active. If Fleet cannot reach this Mac, install/start the Homebrew tailscaled daemon later." >&2
    return 1
  fi
  if ! command -v brew >/dev/null 2>&1; then
    echo "Homebrew is required for the managed macOS tailscaled setup." >&2
    return 1
  fi
  if ! homebrew_tailscale_formula_installed; then
    echo "Installing Homebrew Tailscale CLI/daemon"
    HOMEBREW_NO_INSTALL_CLEANUP=1 brew install --formula tailscale
  fi
  echo "Restarting Homebrew tailscaled service"
  quit_macos_tailscale_gui
  if ! sudo brew services restart tailscale; then
    echo "Could not restart the Homebrew tailscaled service." >&2
    return 1
  fi
  local formula_cli
  formula_cli="$(homebrew_tailscale_cli)"
  if [[ -z "$formula_cli" ]]; then
    echo "Homebrew tailscale CLI was not found after install/start." >&2
    return 1
  fi
  export HIVE_TAILSCALE_CLI="$formula_cli"
  echo "Connecting Homebrew tailscaled"
  if ! connect_homebrew_tailscaled "$formula_cli"; then
    echo "Homebrew tailscaled did not finish connecting before the auth wait timed out." >&2
    return 1
  fi
  if ! run_with_timeout 10 run_tailscale_cli_sudo "$formula_cli" status >/dev/null 2>&1; then
    echo "Homebrew tailscaled started, but status did not respond quickly." >&2
    return 1
  fi
  echo "Homebrew tailscaled is connected"
}

enable_tailscale_ssh() {
  if ! tailscale_status_connected; then
    return
  fi
  local cli help_output=""
  while IFS= read -r cli; do
    [[ -n "$cli" ]] || continue
    help_output="$(run_tailscale_cli "$cli" set --help 2>&1 || true)"
    [[ "$help_output" == *"--ssh"* ]] && break
  done < <(tailscale_cli_candidates | awk '!seen[$0]++')
  if [[ "$help_output" != *"--ssh"* ]]; then
    echo "This Tailscale version does not support Tailscale SSH." >&2
    return
  fi
  if tailscale_prefs_has '"RunSSH": true'; then
    echo "Tailscale SSH already advertised by this machine"
    return
  fi
  local tailscale_ssh_error=""
  cli="$(tailscale_cli_candidates | awk '!seen[$0]++ { print; exit }')"
  if [[ -n "$cli" ]] && tailscale_ssh_error="$(run_tailscale_cli "$cli" set --ssh=true 2>&1)"; then
    echo "Tailscale SSH advertised by this machine"
  elif [[ -n "$cli" ]] && command -v sudo >/dev/null 2>&1 && tailscale_sudo_error="$(run_tailscale_cli_sudo_noninteractive "$cli" set --ssh=true 2>&1)"; then
    echo "Tailscale SSH advertised by this machine"
  else
    if [[ -n "${tailscale_sudo_error:-}" && "$tailscale_ssh_error" != *"sandboxed Tailscale GUI builds"* ]]; then
      tailscale_ssh_error="$tailscale_sudo_error"
    fi
    echo "Could not advertise Tailscale SSH automatically." >&2
    if [[ -n "$tailscale_ssh_error" ]]; then
      echo "Tailscale said: $(printf "%s" "$tailscale_ssh_error" | tr '\n' ' ' | sed 's/[[:space:]]\{1,\}/ /g')" >&2
    fi
    if [[ "$tailscale_ssh_error" == *"sandboxed Tailscale GUI builds"* ]]; then
      echo "This macOS Tailscale build cannot host Tailscale SSH. Shared-brain Syncthing can still work, but Tailscale SSH features from this Mac are disabled." >&2
      echo "Fleet collector discovery does not require Tailscale SSH; it uses normal Tailnet HTTP on port $PORT." >&2
      echo "Homebrew tailscaled is installed, but the active CLI call still reached the sandboxed GUI backend." >&2
      if setup_homebrew_tailscaled_for_fleet; then
        enable_tailscale_ssh
      fi
    else
      echo "Run on this machine if prompted for admin rights: sudo tailscale set --ssh" >&2
    fi
    return
  fi
  if ! tailscale_prefs_has '"RunSSH": true'; then
    echo "Tailscale accepted the SSH setting, but verification did not report RunSSH=true yet." >&2
  fi
}

maybe_enable_system_tailnet_collector_serve() {
  [[ "$SYSTEM_TAILNET_SERVE_ACTIVE" == "true" ]] || return 0
  tailscale_status_connected || return 0

  local cli output=""
  cli="$(tailscale_cli_candidates | awk '!seen[$0]++ { print; exit }')"
  [[ -n "$cli" ]] || return 0

  if output="$(run_tailscale_cli "$cli" serve --bg --http "$TAILNET_COLLECTOR_PORT" "http://localhost:$PORT" 2>&1)"; then
    echo "Tailnet collector URL: http://<this-machine>:$TAILNET_COLLECTOR_PORT"
    return
  fi
  if output="$(run_tailscale_cli_sudo_noninteractive "$cli" serve --bg --http "$TAILNET_COLLECTOR_PORT" "http://localhost:$PORT" 2>&1)"; then
    echo "Tailnet collector URL: http://<this-machine>:$TAILNET_COLLECTOR_PORT"
    return
  fi

  echo "Could not enable Tailscale Serve for the collector on Tailnet port $TAILNET_COLLECTOR_PORT." >&2
  if [[ -n "$output" ]]; then
    echo "Tailscale said: $(printf "%s" "$output" | tr '\n' ' ' | sed 's/[[:space:]]\{1,\}/ /g')" >&2
  fi
}

stop_existing_listener() {
  local pids=""
  if command -v lsof >/dev/null 2>&1; then
    pids="$(lsof -tiTCP:"$PORT" -sTCP:LISTEN 2>/dev/null || true)"
  elif command -v fuser >/dev/null 2>&1; then
    pids="$(fuser "$PORT/tcp" 2>/dev/null || true)"
  fi
  if [[ -n "$pids" ]]; then
    echo "Stopping existing collector listener on port $PORT: $pids"
    kill $pids >/dev/null 2>&1 || true
    sleep 1
    if [[ -n "$(port_listener_pids "$PORT")" ]]; then
      kill -9 $(port_listener_pids "$PORT") >/dev/null 2>&1 || true
      sleep 1
    fi
  fi
}

port_listener_pids() {
  local port="$1"
  if command -v lsof >/dev/null 2>&1; then
    lsof -tiTCP:"$port" -sTCP:LISTEN 2>/dev/null || true
  elif command -v fuser >/dev/null 2>&1; then
    fuser "$port/tcp" 2>/dev/null || true
  fi
}

collector_health_is_hivemind() {
  local port="$1"
  local body
  body="$(curl -fsS --max-time 2 "http://127.0.0.1:$port/health" 2>/dev/null || true)"
  [[ -n "$body" ]] || return 1
  printf "%s" "$body" | node -e '
let d = "";
process.stdin.on("data", c => d += c);
process.stdin.on("end", () => {
  try {
    const j = JSON.parse(d);
    process.exit(j?.version?.appDir || j?.capabilities?.runtimes ? 0 : 1);
  } catch {
    process.exit(1);
  }
});
' >/dev/null 2>&1
}

link_control_is_hivemind() {
  local control="$1"
  local body
  body="$(curl -fsS --max-time 2 "http://$control/status" 2>/dev/null || true)"
  [[ -n "$body" ]] || return 1
  printf "%s" "$body" | node -e '
let d = "";
process.stdin.on("data", c => d += c);
process.stdin.on("end", () => {
  try {
    const j = JSON.parse(d);
    process.exit(j && (j.backendState || j.magicDnsSuffix || j.self || j.peer) ? 0 : 1);
  } catch {
    process.exit(1);
  }
});
' >/dev/null 2>&1
}

choose_nearest_available_port() {
  local start_port="$1"
  local max_attempts="${2:-200}"
  local reserved_port="${3:-}"
  local candidate
  local offset
  for (( offset = 0; offset < max_attempts; offset++ )); do
    candidate=$((start_port + offset))
    [[ -n "$reserved_port" && "$candidate" == "$reserved_port" ]] && continue
    if [[ -z "$(port_listener_pids "$candidate")" ]]; then
      printf "%s" "$candidate"
      return 0
    fi
  done
  return 1
}

choose_link_local_collector_port() {
  local listener
  listener="$(port_listener_pids "$PORT")"
  if [[ -z "$listener" ]] || collector_health_is_hivemind "$PORT"; then
    return
  fi

  local requested_port="$PORT"
  local candidate
  candidate="$(choose_nearest_available_port "$requested_port" 200 || true)"
  if [[ -n "$candidate" ]]; then
    if [[ "$LINK_ACTIVE" == "true" ]]; then
      echo "Port $requested_port is already used by another local service, so HivemindOS will run its private collector on the next available port: 127.0.0.1:$candidate."
      echo "Hivemind Link will still expose this machine to the Tailnet on port $LINK_TAILNET_PORT."
    else
      echo "Port $requested_port is already used by another local service, so HivemindOS will use the next available collector port: $candidate."
    fi
    PORT="$candidate"
    return
  fi

  echo "Port $requested_port is already used by another local service, and no nearby collector port was free." >&2
  echo "Stop the process on $requested_port or set AGENT_TELEMETRY_PORT to a free local port before rerunning setup." >&2
  exit 1
}

choose_system_tailnet_collector_port() {
  [[ "$LINK_ACTIVE" != "true" && "$TAILNET_SYNC_ENABLED" == "true" ]] || return 0
  [[ "$PORT" == "$TAILNET_COLLECTOR_PORT" ]] || return 0

  local candidate
  candidate="$(choose_nearest_available_port "$((TAILNET_COLLECTOR_PORT + 2))" 200 "$TAILNET_COLLECTOR_PORT" || true)"
  if [[ -z "$candidate" ]]; then
    echo "No nearby private collector port was free for Full Tailnet mode." >&2
    echo "Stop the process on $TAILNET_COLLECTOR_PORT or set AGENT_TELEMETRY_PORT to a free local port before rerunning setup." >&2
    exit 1
  fi

  echo "Full Tailnet mode will publish the collector on Tailnet port $TAILNET_COLLECTOR_PORT and run the private local collector on 127.0.0.1:$candidate."
  PORT="$candidate"
  SYSTEM_TAILNET_SERVE_ACTIVE="true"
}

choose_link_control_port() {
  [[ "$LINK_ACTIVE" == "true" ]] || return 0
  local host="${LINK_CONTROL%:*}"
  local port="${LINK_CONTROL##*:}"
  if [[ -z "$host" || "$host" == "$LINK_CONTROL" || -z "$port" ]]; then
    echo "Invalid HIVE_LINK_CONTROL value: $LINK_CONTROL" >&2
    echo "Use host:port, for example 127.0.0.1:8788." >&2
    exit 1
  fi

  local listener
  listener="$(port_listener_pids "$port")"
  if [[ -z "$listener" ]] || link_control_is_hivemind "$LINK_CONTROL"; then
    LINK_CONTROL_STATUS_URL="http://$LINK_CONTROL/status"
    LINK_CONTROL_HEALTH_URL="http://$LINK_CONTROL/health"
    return
  fi

  local candidate
  candidate="$(choose_nearest_available_port "$port" 200 "$PORT" || true)"
  if [[ -n "$candidate" ]]; then
    echo "Port $port is already used by another local service, so Hivemind Link will run its control API on the next available port: $host:$candidate."
    LINK_CONTROL="$host:$candidate"
    LINK_CONTROL_STATUS_URL="http://$LINK_CONTROL/status"
    LINK_CONTROL_HEALTH_URL="http://$LINK_CONTROL/health"
    return
  fi

  echo "Port $port is already used by another local service, and no nearby Hivemind Link control port was free." >&2
  echo "Stop the process on $port or set HIVE_LINK_CONTROL to a free host:port before rerunning setup." >&2
  exit 1
}

choose_link_tailnet_port() {
  [[ "$LINK_ACTIVE" == "true" ]] || return 0
  # hivemind-linkd's tailnet listener lives inside its own tsnet userspace
  # netstack: it binds no host port at all, so a local process on the same
  # port NUMBER can never collide with it. The canonical Tailnet port stays
  # pinned (default 8787) so peers (fleet discovery, hive-env sync, the
  # watchdog) find every machine at a predictable address instead of chasing
  # per-machine drift; override only via HIVE_LINK_TAILNET_PORT.
  if [[ -n "${HIVE_LINK_TAILNET_PORT:-}" ]]; then
    echo "Hivemind Link Tailnet port explicitly set to $LINK_TAILNET_PORT (HIVE_LINK_TAILNET_PORT)."
  fi
  return 0
}

run_with_timeout() {
  local seconds="$1"
  shift
  "$@" &
  local pid="$!"
  local elapsed=0
  while kill -0 "$pid" >/dev/null 2>&1; do
    if (( elapsed >= seconds )); then
      kill "$pid" >/dev/null 2>&1 || true
      sleep 1
      kill -9 "$pid" >/dev/null 2>&1 || true
      wait "$pid" >/dev/null 2>&1 || true
      return 124
    fi
    sleep 1
    elapsed=$((elapsed + 1))
  done
  wait "$pid"
}

launchctl_bounded() {
  local seconds="$1"
  shift
  if ! run_with_timeout "$seconds" launchctl "$@"; then
    echo "launchctl $* did not finish quickly; continuing setup." >&2
    return 1
  fi
}

launchctl_quiet() {
  local seconds="$1"
  shift
  launchctl_bounded "$seconds" "$@" >/dev/null 2>&1
}

prompt_yes_no() {
  local question="$1"
  local default="${2:-yes}"
  local answer=""
  if [[ ! -t 0 || ! -t 1 ]]; then
    [[ "$default" == "yes" ]]
    return
  fi
  if [[ "$default" == "yes" ]]; then
    read -r -p "$question [Y/n] " answer
    [[ ! "$answer" =~ ^[Nn] ]]
  else
    read -r -p "$question [y/N] " answer
    [[ "$answer" =~ ^[Yy] ]]
  fi
}

hivemind_link_log_has_stale_identity() {
  grep -aEqi 'Authorization failed|already exists|node nodekey:.*already exists' \
    "$HOME/Library/Logs/hivemindos-linkd.err.log" \
    "$HOME/Library/Logs/hivemindos-linkd.log" 2>/dev/null
}

hivemind_link_status() {
  curl -fsS --max-time 3 "http://$LINK_CONTROL/status" 2>/dev/null || true
}

hivemind_link_connected_name() {
  node -e 'let d="";process.stdin.on("data",c=>d+=c);process.stdin.on("end",()=>{try{const j=JSON.parse(d); if(j.ok) console.log(j.self?.DNSName || j.self?.HostName || "connected")}catch{}})' 2>/dev/null
}

hivemind_link_auth_url() {
  node -e 'let d="";process.stdin.on("data",c=>d+=c);process.stdin.on("end",()=>{try{const j=JSON.parse(d); if(j.authUrl) console.log(j.authUrl)}catch{}})' 2>/dev/null
}

hivemind_link_backend_state() {
  node -e 'let d="";process.stdin.on("data",c=>d+=c);process.stdin.on("end",()=>{try{const j=JSON.parse(d); if(j.backendState) console.log(j.backendState)}catch{}})' 2>/dev/null
}

wait_for_hivemind_link_status() {
  local seconds="${1:-20}"
  local elapsed=0
  LINK_STATUS=""
  while (( elapsed < seconds )); do
    LINK_STATUS="$(hivemind_link_status)"
    if [[ -n "$LINK_STATUS" ]] && printf "%s" "$LINK_STATUS" | node -e 'let d="";process.stdin.on("data",c=>d+=c);process.stdin.on("end",()=>{try{const j=JSON.parse(d); process.exit(j.authUrl || j.ok ? 0 : 1)}catch{process.exit(1)}})' 2>/dev/null; then
      return 0
    fi
    if hivemind_link_log_has_stale_identity; then
      return 2
    fi
    sleep 1
    elapsed=$((elapsed + 1))
  done
  return 1
}

stop_hivemind_link_service() {
  if [[ "$(uname -s)" == "Darwin" ]]; then
    local plist="${LINK_PLIST:-$HOME/Library/LaunchAgents/$LINK_LABEL.plist}"
    launchctl_quiet 5 bootout "gui/$(id -u)/$LINK_LABEL" || launchctl_quiet 5 unload "$plist" || true
    launchctl_quiet 5 bootout "gui/$(id -u)/$LINK_LEGACY_LABEL" || launchctl_quiet 5 unload "$HOME/Library/LaunchAgents/$LINK_LEGACY_LABEL.plist" || true
    pkill -x hivemind-linkd >/dev/null 2>&1 || true
  elif command -v systemctl >/dev/null 2>&1; then
    systemctl --user stop hivemindos-linkd.service >/dev/null 2>&1 || true
    pkill -x hivemind-linkd >/dev/null 2>&1 || true
  else
    pkill -x hivemind-linkd >/dev/null 2>&1 || true
  fi
}

reset_hivemind_link_state() {
  local state_path="$LINK_STATE_DIR"
  local backup_path=""
  stop_hivemind_link_service
  if [[ -e "$state_path" ]]; then
    backup_path="$state_path.bak.$(date +%Y%m%d-%H%M%S)"
    mv "$state_path" "$backup_path"
    echo "Hivemind Link had stale Tailscale sign-in state, so setup reset it automatically."
    echo "Note: the previous Tailscale node registration stays on the tailnet as an offline duplicate."
    echo "The dashboard lists it at /api/tailscale/cleanup once it has been offline past the stale window;"
    echo "set HIVE_TAILNET_AUTO_CLEANUP=1 in ~/.hivemindos/.env (with TAILSCALE_API_KEY) to prune such nodes automatically."
  fi
  if [[ "$(uname -s)" == "Darwin" ]]; then
    : > "$HOME/Library/Logs/hivemindos-linkd.log" 2>/dev/null || true
    : > "$HOME/Library/Logs/hivemindos-linkd.err.log" 2>/dev/null || true
  fi
}

hivemind_link_hostname_slug() {
  local raw
  raw="$(hostname 2>/dev/null || printf "machine")"
  raw="${raw%.local}"
  printf "%s" "$raw" | tr '[:upper:]' '[:lower:]' | sed -E 's/[^a-z0-9-]+/-/g; s/^-+//; s/-+$//'
}

prepare_hivemind_link_state_dir() {
  [[ "$LINK_ACTIVE" == "true" ]] || return
  [[ -n "$LINK_STATE_DIR" ]] || return
  if [[ -s "$LINK_STATE_DIR/tailscaled.state" ]]; then
    return
  fi

  local slug legacy_state legacy_parent candidate
  slug="$(hivemind_link_hostname_slug)"
  legacy_parent="$HOME/.hivemindos/link"
  legacy_state="$legacy_parent/hivemindos-${slug}"
  if [[ -s "$legacy_state/tailscaled.state" ]]; then
    mkdir -p "$(dirname "$LINK_STATE_DIR")"
    cp -pR "$legacy_state" "$LINK_STATE_DIR"
    echo "Migrated Hivemind Link state to stable path: $LINK_STATE_DIR"
    return
  fi

  candidate="$(find "$legacy_parent" -mindepth 1 -maxdepth 1 -type d -name 'hivemindos-*' -exec sh -c 'for d do s="$d/tailscaled.state"; [ -s "$s" ] && [ "$(wc -c < "$s")" -gt 1000 ] && printf "%s\t%s\n" "$(stat -f %m "$s" 2>/dev/null || stat -c %Y "$s" 2>/dev/null || echo 0)" "$d"; done; exit 0' sh {} + 2>/dev/null | sort -rn | awk 'NR==1 {print $2}' || true)"
  if [[ -n "$candidate" ]]; then
    mkdir -p "$(dirname "$LINK_STATE_DIR")"
    cp -pR "$candidate" "$LINK_STATE_DIR"
    echo "Migrated existing Hivemind Link state to stable path: $LINK_STATE_DIR"
  fi
}

start_hivemind_link_service() {
  if [[ "$(uname -s)" == "Darwin" ]]; then
    launchctl_quiet 5 bootout "gui/$(id -u)/$LINK_LEGACY_LABEL" || launchctl_quiet 5 unload "$HOME/Library/LaunchAgents/$LINK_LEGACY_LABEL.plist" || true
    rm -f "$HOME/Library/LaunchAgents/$LINK_LEGACY_LABEL.plist"
    launchctl_quiet 5 bootout "gui/$(id -u)/$LINK_LABEL" || launchctl_quiet 5 unload "$LINK_PLIST" || true
    pkill -x hivemind-linkd >/dev/null 2>&1 || true
    launchctl_quiet 5 bootstrap "gui/$(id -u)" "$LINK_PLIST" || launchctl_quiet 5 load "$LINK_PLIST" || true
    launchctl_quiet 5 kickstart -k "gui/$(id -u)/$LINK_LABEL" || true
  elif command -v systemctl >/dev/null 2>&1; then
    systemctl --user daemon-reload
    systemctl --user enable hivemindos-linkd.service >/dev/null
    systemctl --user restart hivemindos-linkd.service
  fi
}

wait_for_hivemind_link_auth_confirmation() {
  if [[ ! -t 0 || ! -t 1 ]]; then
    return 0
  fi
  printf "Press Enter once you've signed in to Hivemind Link. "
  read -r _ || true
  echo "Checking the connection..."
  for _ in $(seq 1 12); do
    local status connected_name
    status="$(hivemind_link_status)"
    connected_name="$(printf "%s" "$status" | hivemind_link_connected_name || true)"
    if [[ -n "$connected_name" ]]; then
      echo "Hivemind Link connected: $connected_name"
      return 0
    fi
    if hivemind_link_log_has_stale_identity; then
      return 2
    fi
    sleep 2
  done
  echo "Hivemind Link is still connecting. You can continue; the dashboard will pick it up automatically." >&2
}

collector_local_health() {
  collector_health_is_hivemind "$PORT"
}

wait_for_local_collector() {
  local seconds="${1:-10}"
  local elapsed=0
  while (( elapsed < seconds )); do
    if collector_local_health; then
      return 0
    fi
    sleep 1
    elapsed=$((elapsed + 1))
  done
  return 1
}

# Allow the collector's Node binary to accept INBOUND connections through the
# macOS Application Firewall. This is about network reachability of the collector
# from other machines' dashboards — it is unrelated to the gateway's file-access
# (TCC) grant, which the app-signed login item handles. Only matters when the
# collector binds 0.0.0.0 (a --system-tailscale install without tailscale serve).
maybe_allow_node_through_macos_firewall() {
  if [[ "$(uname -s)" != "Darwin" || ! -x /usr/libexec/ApplicationFirewall/socketfilterfw ]]; then
    return
  fi
  if ! prompt_yes_no "Allow this collector's Node binary through the macOS firewall for Tailnet dashboards?" "yes"; then
    echo "Skipping macOS firewall allow-list. If another dashboard cannot reach this collector, allow incoming connections for: $NODE_BIN" >&2
    return
  fi
  if command -v sudo >/dev/null 2>&1; then
    sudo /usr/libexec/ApplicationFirewall/socketfilterfw --add "$NODE_BIN" >/dev/null 2>&1 || true
    sudo /usr/libexec/ApplicationFirewall/socketfilterfw --unblockapp "$NODE_BIN" >/dev/null 2>&1 || true
    echo "Allowed Node collector binary through macOS firewall: $NODE_BIN"
  else
    echo "sudo is unavailable; allow incoming connections for this Node binary manually: $NODE_BIN" >&2
  fi
}

maybe_disable_tailscale_shields_up() {
  if ! tailscale_status_connected; then
    return
  fi
  if ! tailscale_prefs_has '"ShieldsUp": true'; then
    return
  fi
  echo "Tailscale Shields Up is enabled; other Tailnet machines cannot reach this collector while it is on." >&2
  if ! prompt_yes_no "Disable Tailscale Shields Up now so Fleet dashboards can reach this collector?" "yes"; then
    echo "Leaving Shields Up enabled. Disable later with: tailscale set --shields-up=false" >&2
    return
  fi
  local cli
  cli="$(tailscale_cli_candidates | awk '!seen[$0]++ { print; exit }')"
  if [[ -n "$cli" ]] && run_tailscale_cli "$cli" set --shields-up=false >/dev/null 2>&1; then
    echo "Disabled Tailscale Shields Up"
  elif [[ -n "$cli" ]] && command -v sudo >/dev/null 2>&1 && run_tailscale_cli_sudo "$cli" set --shields-up=false >/dev/null 2>&1; then
    echo "Disabled Tailscale Shields Up"
  else
    echo "Could not disable Shields Up automatically. Run: tailscale set --shields-up=false" >&2
  fi
}

hermes_api_healthy() {
  curl -fsS --max-time 2 "http://$HERMES_API_HOST:$HERMES_API_PORT/health" >/dev/null 2>&1
}

should_apply_hermes_gateway_change() {
  case "$HERMES_RESTART_MODE" in
    later|skip|no|0|false)
      echo "Hermes API settings were updated. Start or restart Hermes later so the API server settings take effect." >&2
      return 1
      ;;
    ask)
      if [[ -t 0 && -t 1 ]]; then
        echo
        echo "Hermes API settings were updated for dashboard chat bridging."
        echo "The Hermes gateway must be started or restarted before those settings take effect."
        read -r -p "Start/restart Hermes gateway now? [Y/n] " answer
        case "$answer" in
          n|N|no|NO|No)
            echo "Skipping Hermes gateway start/restart. Run 'hermes gateway start' later to enable dashboard chat bridging." >&2
            return 1
            ;;
        esac
      fi
      return 0
      ;;
    *)
      return 0
      ;;
  esac
}

wait_for_hermes_api() {
  local seconds="${1:-5}"
  local elapsed=0
  while (( elapsed < seconds )); do
    if hermes_api_healthy; then
      return 0
    fi
    sleep 1
    elapsed=$((elapsed + 1))
  done
  return 1
}

activate_hermes_gateway() {
  local status
  status="$(hermes gateway status 2>&1 || true)"
  if printf "%s" "$status" | grep -qi "not running"; then
    echo "Starting Hermes gateway so the API server settings take effect"
    run_with_timeout 10 hermes gateway start >/dev/null 2>&1
    return
  fi

  echo "Restarting Hermes gateway so the API server settings take effect"
  run_with_timeout 5 hermes gateway stop >/dev/null 2>&1 || true
  run_with_timeout 10 hermes gateway start >/dev/null 2>&1
}

# Hermes' built-in API server (the dashboard <-> agent chat bridge on
# 127.0.0.1:8642) REFUSES to start without a non-empty API_SERVER_KEY, and Hermes
# never auto-generates one. Without a key the API server never comes up, the
# health guard in configure_hermes_api_server never trips, and every installer /
# fleet auto-repair run restarts the gateway — the endless "gateway shutting
# down" Telegram spam. Generate a real key once, persist it where the gateway
# reads it (~/.hermes/.env, loaded with override=true at gateway start), and
# reuse it on every later run. Sets HERMES_API_KEY_VALUE (for collector wiring)
# and HERMES_API_KEY_GENERATED (1 only when a NEW key was just created).
ensure_hermes_api_server_key() {
  command -v hermes >/dev/null 2>&1 || return 0

  local env_path config_path existing
  env_path="$(hermes config env-path 2>/dev/null || true)"
  [ -n "$env_path" ] || env_path="$HOME/.hermes/.env"
  config_path="$(hermes config path 2>/dev/null || true)"
  [ -n "$config_path" ] || config_path="$HOME/.hermes/config.yaml"

  # Reuse an existing usable key (>=16 chars) from .env, or fall back to the
  # legacy config.yaml location `hermes config set` would have written it to.
  existing="$(grep -E '^API_SERVER_KEY=' "$env_path" 2>/dev/null | tail -1 | cut -d= -f2- | tr -d ' \t\r"' || true)"
  if [ -z "$existing" ]; then
    existing="$(grep -E '^[[:space:]]*API_SERVER_KEY:' "$config_path" 2>/dev/null | tail -1 | sed -E 's/^[[:space:]]*API_SERVER_KEY:[[:space:]]*//' | tr -d ' \t\r"' || true)"
  fi
  if [ -n "$existing" ] && [ "${#existing}" -ge 16 ]; then
    HERMES_API_KEY_VALUE="$existing"
    HERMES_API_KEY_GENERATED=0
    return 0
  fi

  # Generate a fresh 32-byte hex key (matches the proven working-machine layout).
  local key=""
  if command -v openssl >/dev/null 2>&1; then key="$(openssl rand -hex 32 2>/dev/null || true)"; fi
  if [ -z "$key" ] && command -v python3 >/dev/null 2>&1; then key="$(python3 -c 'import secrets;print(secrets.token_hex(32))' 2>/dev/null || true)"; fi
  if [ -z "$key" ]; then key="$(head -c 32 /dev/urandom 2>/dev/null | od -An -tx1 | tr -d ' \n' || true)"; fi
  if [ -z "$key" ]; then
    echo "Could not generate an API_SERVER_KEY for the Hermes API bridge; skipping (dashboard chat bridging may stay unavailable)." >&2
    return 0
  fi

  # Persist into ~/.hermes/.env, replacing any stale/blank API_SERVER_KEY line
  # (preserve the file's perms/inode by rewriting through cat, not mv).
  mkdir -p "$(dirname "$env_path")"
  [ -f "$env_path" ] || { : > "$env_path"; chmod 600 "$env_path" 2>/dev/null || true; }
  local tmp; tmp="$(mktemp)"
  grep -v '^API_SERVER_KEY=' "$env_path" 2>/dev/null > "$tmp" || true
  printf 'API_SERVER_KEY=%s\n' "$key" >> "$tmp"
  cat "$tmp" > "$env_path"
  rm -f "$tmp"

  HERMES_API_KEY_VALUE="$key"
  HERMES_API_KEY_GENERATED=1
  echo "Generated and persisted a Hermes API_SERVER_KEY for dashboard chat bridging."
}

configure_hermes_api_server() {
  if ! command -v hermes >/dev/null 2>&1; then
    return
  fi

  # Resolve/generate the API key FIRST so the collector service can be wired with
  # it (below) even when the gateway is already healthy.
  ensure_hermes_api_server_key

  if hermes_api_healthy; then
    echo "Hermes API server is already healthy"
    return
  fi

  echo "Configuring Hermes API server on $HERMES_API_HOST:$HERMES_API_PORT"
  hermes config set API_SERVER_ENABLED true >/dev/null || echo "Could not set API_SERVER_ENABLED; continuing" >&2
  hermes config set API_SERVER_HOST "$HERMES_API_HOST" >/dev/null || echo "Could not set API_SERVER_HOST; continuing" >&2
  hermes config set API_SERVER_PORT "$HERMES_API_PORT" >/dev/null || echo "Could not set API_SERVER_PORT; continuing" >&2

  # Restart the gateway to apply settings — but ONLY when we just generated the
  # key, or we have not yet recorded a restart attempt for this bridge. Once a
  # usable key exists and we have restarted once, never restart again on a still-
  # unhealthy probe: restarting cannot fix a different root cause, and doing it on
  # every run is exactly what produced the endless "gateway shutting down" loop.
  if should_apply_hermes_gateway_change; then
    if [ "$HERMES_API_KEY_GENERATED" = "1" ] || [ ! -f "$HERMES_BRIDGE_RESTART_MARKER" ]; then
      if activate_hermes_gateway; then
        mkdir -p "$(dirname "$HERMES_BRIDGE_RESTART_MARKER")"
        : > "$HERMES_BRIDGE_RESTART_MARKER"
      else
        echo "Hermes gateway did not start quickly; continuing setup. Run 'hermes gateway start' later if dashboard chat bridging is not healthy." >&2
      fi
    else
      echo "Hermes API server still unhealthy but already configured with a key and restarted once; not restarting again to avoid a restart loop. Check 'hermes gateway' logs." >&2
    fi
  fi

  if wait_for_hermes_api 5; then
    echo "Hermes API server is healthy"
  else
    echo "Hermes API server is not healthy yet; collector /chat will report this if delegation is attempted." >&2
  fi
}

configure_hermes_api_server

# Inject the Hermes API bridge key into the collector service env so the
# collector's authenticated /chat proxy (Authorization: Bearer) can reach the
# now key-protected Hermes API server, and so its ensureHermesApiServer fallback
# spawns a gateway with the matching key instead of a second, conflicting one.
# Only inject a token-shaped value; an empty entry collapses to a blank line.
HERMES_API_KEY_PLIST_ENTRY=""
HERMES_API_KEY_SYSTEMD_ENTRY=""
if [[ -n "$HERMES_API_KEY_VALUE" && "$HERMES_API_KEY_VALUE" =~ ^[A-Za-z0-9._~+/=-]+$ ]]; then
  HERMES_API_KEY_PLIST_ENTRY="    <key>AGENT_TELEMETRY_HERMES_API_KEY</key><string>$HERMES_API_KEY_VALUE</string>"
  HERMES_API_KEY_SYSTEMD_ENTRY="Environment=AGENT_TELEMETRY_HERMES_API_KEY=$HERMES_API_KEY_VALUE"
fi

LINK_ACTIVE="false"
if build_hivemind_linkd_if_enabled; then
  LINK_ACTIVE="true"
elif [[ "$LINK_ENABLED" == "true" ]]; then
  echo "Hivemind Link was requested but could not be built; falling back to the normal collector network mode." >&2
fi

TAILNET_SYNC_ENABLED="false"
if [[ "$LINK_ACTIVE" == "true" ]]; then
  TAILNET_SYNC_ENABLED="false"
  choose_link_control_port
  choose_link_tailnet_port
elif [[ "$NETWORK_MANAGED_BY_SETUP" == "true" ]]; then
  TAILNET_SYNC_ENABLED="$SETUP_TAILNET_SYNC_ENABLED"
elif ensure_tailscale_connected; then
  TAILNET_SYNC_ENABLED="true"
else
  echo "Tailscale setup was not completed; Hivemind Sync is disabled for this run. Local collector features will still work." >&2
fi
choose_system_tailnet_collector_port
choose_link_local_collector_port

if [[ "$(uname -s)" == "Darwin" ]]; then
  SYNCTHING_PLIST="$HOME/Library/LaunchAgents/com.hivemindos.syncthing.plist"
  LEGACY_SYNCTHING_PLIST="$HOME/Library/LaunchAgents/com.omni-agent-hivemind.syncthing.plist"
  launchctl_bounded 5 bootout "gui/$(id -u)/com.omni-agent-hivemind.syncthing" >/dev/null 2>&1 || launchctl_bounded 5 unload "$LEGACY_SYNCTHING_PLIST" >/dev/null 2>&1 || true
  rm -f "$LEGACY_SYNCTHING_PLIST"
  if [[ "$TAILNET_SYNC_ENABLED" == "true" || -f "$SYNCTHING_PLIST" ]]; then
    install_syncthing_if_missing
    if command -v syncthing >/dev/null 2>&1; then
      SYNCTHING_BIN="$(command -v syncthing)"
      SYNCTHING_HELPER="$(resolve_macos_sync_helper || true)"
      SYNCTHING_HELP="$("$SYNCTHING_BIN" --help 2>/dev/null || true)"
      if grep -q '^  serve ' <<<"$SYNCTHING_HELP"; then
        SYNCTHING_ARGUMENTS="    <string>serve</string>
    <string>--no-browser</string>
    <string>--gui-address=127.0.0.1:8384</string>"
      else
        SYNCTHING_ARGUMENTS="    <string>-no-browser</string>
    <string>-gui-address=127.0.0.1:8384</string>"
      fi
      if [[ -n "$SYNCTHING_HELPER" && -x "$SYNCTHING_HELPER" ]]; then
        SYNCTHING_PROGRAM_ARGUMENTS="    <string>$SYNCTHING_HELPER</string>
    <string>$SYNCTHING_BIN</string>
$SYNCTHING_ARGUMENTS"
      else
        SYNCTHING_PROGRAM_ARGUMENTS="    <string>$SYNCTHING_BIN</string>
$SYNCTHING_ARGUMENTS"
      fi
      mkdir -p "$(dirname "$SYNCTHING_PLIST")"
      cat > "$SYNCTHING_PLIST" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key><string>com.hivemindos.syncthing</string>
  <key>ProgramArguments</key>
  <array>
$SYNCTHING_PROGRAM_ARGUMENTS
  </array>
  <key>EnvironmentVariables</key>
  <dict>
    <key>SYNCTHING_GUI_ADDRESS</key><string>127.0.0.1:8384</string>
  </dict>
  <key>RunAtLoad</key><true/>
  <key>KeepAlive</key><true/>
  <key>StandardOutPath</key><string>$HOME/Library/Logs/hivemindos-syncthing.log</string>
  <key>StandardErrorPath</key><string>$HOME/Library/Logs/hivemindos-syncthing.err.log</string>
</dict>
</plist>
PLIST
      launchctl_bounded 5 unload "$SYNCTHING_PLIST" >/dev/null 2>&1 || true
      launchctl_bounded 5 load "$SYNCTHING_PLIST"
      launchctl_bounded 5 kickstart -k "gui/$(id -u)/com.hivemindos.syncthing" >/dev/null 2>&1 || true
      echo "Installed Syncthing macOS LaunchAgent on 127.0.0.1:8384"
    else
      echo "Syncthing is unavailable; Hivemind Sync shared-brain folder sync is disabled." >&2
    fi
  fi

  PLIST="$HOME/Library/LaunchAgents/com.agent-control-room.telemetry.plist"
  mkdir -p "$(dirname "$PLIST")"
  COLLECTOR_PROGRAM_ARGUMENTS="$(resolve_macos_collector_program_arguments)"
  cat > "$PLIST" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key><string>com.agent-control-room.telemetry</string>
  <key>ProgramArguments</key>
  <array>
    $COLLECTOR_PROGRAM_ARGUMENTS
  </array>
  <key>EnvironmentVariables</key>
  <dict>
    <key>AGENT_TELEMETRY_PORT</key><string>$PORT</string>
    <key>AGENT_TELEMETRY_HOST</key><string>$( [[ "$LINK_ACTIVE" == "true" || "$SYSTEM_TAILNET_SERVE_ACTIVE" == "true" ]] && printf "127.0.0.1" || printf "0.0.0.0" )</string>
    <key>AGENT_TELEMETRY_HERMES_API_HOST</key><string>$HERMES_API_HOST</string>
    <key>AGENT_TELEMETRY_HERMES_API_PORT</key><string>$HERMES_API_PORT</string>
$HERMES_API_KEY_PLIST_ENTRY
    <key>HIVE_COLLECTOR_ONLY</key><string>$COLLECTOR_ONLY</string>
  </dict>
  <key>RunAtLoad</key><true/>
  <!-- KeepAlive also powers auto-reload: the collector watches its own source
       and exits on change, so launchd relaunches it with the new code (see
       startSelfReloadWatcher in agent-telemetry-collector.mjs). -->
  <key>KeepAlive</key><true/>
  <key>StandardOutPath</key><string>$HOME/Library/Logs/agent-telemetry.log</string>
  <key>StandardErrorPath</key><string>$HOME/Library/Logs/agent-telemetry.err.log</string>
</dict>
</plist>
PLIST
  launchctl_quiet 5 bootout "gui/$(id -u)/com.agent-control-room.telemetry" || launchctl_quiet 5 unload "$PLIST" || true
  launchctl_quiet 5 bootstrap "gui/$(id -u)" "$PLIST" || launchctl_quiet 5 load "$PLIST" || true
  launchctl_quiet 5 kickstart -k "gui/$(id -u)/com.agent-control-room.telemetry" || true
  if [[ "$LINK_ACTIVE" == "true" ]]; then
    prepare_hivemind_link_state_dir
    LINK_PLIST="$HOME/Library/LaunchAgents/$LINK_LABEL.plist"
    LEGACY_LINK_PLIST="$HOME/Library/LaunchAgents/$LINK_LEGACY_LABEL.plist"
    launchctl_bounded 5 bootout "gui/$(id -u)/$LINK_LEGACY_LABEL" >/dev/null 2>&1 || launchctl_bounded 5 unload "$LEGACY_LINK_PLIST" >/dev/null 2>&1 || true
    rm -f "$LEGACY_LINK_PLIST"
    cat > "$LINK_PLIST" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key><string>$LINK_LABEL</string>
  <key>ProgramArguments</key>
  <array>
    <string>$LINK_BIN</string>
  </array>
  <key>EnvironmentVariables</key>
  <dict>
    <key>HIVE_LINK_TARGET</key><string>http://127.0.0.1:$PORT</string>
    <key>HIVE_LINK_LISTEN</key><string>:$LINK_TAILNET_PORT</string>
    <key>HIVE_LINK_CONTROL</key><string>$LINK_CONTROL</string>
    <key>HIVE_LINK_STATE_DIR</key><string>$LINK_STATE_DIR</string>
    <key>HIVE_LINK_LOG_FILE</key><string>$LINK_LOG_FILE</string>
    <key>HIVE_LINK_LOG_MAX_BYTES</key><string>$LINK_LOG_MAX_BYTES</string>
    <key>HIVE_LINK_TAILSCALE_DEBUG_LOGS</key><string>$LINK_TAILSCALE_DEBUG_LOGS</string>
    <key>HIVE_LINK_DISABLE_PORTLIST</key><string>$LINK_DISABLE_PORTLIST</string>
    <key>HIVE_LINK_RUN_WEB_CLIENT</key><string>$LINK_RUN_WEB_CLIENT</string>
    <key>HIVE_LINK_EPHEMERAL</key><string>$LINK_EPHEMERAL</string>
    <key>HIVE_LINK_STATUS_TIMEOUT</key><string>$LINK_STATUS_TIMEOUT</string>
    <key>TS_DEBUG_DISABLE_PORTLIST</key><string>$LINK_DISABLE_PORTLIST</string>
  </dict>
  <key>RunAtLoad</key><true/>
  <key>KeepAlive</key><true/>
  <key>StandardOutPath</key><string>$HOME/Library/Logs/hivemindos-linkd.log</string>
  <key>StandardErrorPath</key><string>$HOME/Library/Logs/hivemindos-linkd.err.log</string>
</dict>
</plist>
PLIST
    start_hivemind_link_service
  else
    echo "HivemindOS collector installed."
    maybe_allow_node_through_macos_firewall
  fi
else
  if [[ "$TAILNET_SYNC_ENABLED" == "true" ]]; then
    install_syncthing_if_missing
    if command -v syncthing >/dev/null 2>&1; then
      chmod +x "$SYNCTHING_RUNNER" 2>/dev/null || true
      SYNCTHING_SERVICE="$HOME/.config/systemd/user/hivemindos-syncthing.service"
      mkdir -p "$(dirname "$SYNCTHING_SERVICE")"
      cat > "$SYNCTHING_SERVICE" <<SERVICE
[Unit]
Description=HivemindOS Syncthing folder sync

[Service]
Environment=SYNCTHING_GUI_ADDRESS=127.0.0.1:8384
ExecStart=$SYNCTHING_RUNNER
Restart=always

[Install]
WantedBy=default.target
SERVICE
      systemctl --user daemon-reload
      systemctl --user enable hivemindos-syncthing.service
      systemctl --user restart hivemindos-syncthing.service
      echo "Installed Syncthing systemd user service on 127.0.0.1:8384"
    else
      echo "Syncthing is unavailable; Hivemind Sync shared-brain folder sync is disabled." >&2
    fi
  fi

  # Resilience: Restart=always does NOT cover a clean `systemctl stop`, so if any
  # step between stopping and restarting the collector below aborts (set -euo
  # pipefail), the collector would be left dead (0 agents) until a human
  # intervened — impossible on boxes with no shell access. Guarantee it comes
  # back on exit no matter how this script ends.
  _restore_collector_on_exit() {
    systemctl --user start agent-telemetry.service >/dev/null 2>&1 || true
  }
  trap _restore_collector_on_exit EXIT
  # ROOT-CAUSE FIX (atomic reinstall): prepare everything — write the unit,
  # daemon-reload, enable — while the EXISTING collector keeps RUNNING, and only
  # stop + restart at the very last moment. An abort during the slow/failure-prone
  # steps (unit write, daemon-reload) then leaves the OLD collector serving
  # instead of stranding the machine. The EXIT trap above is the final backstop.
  systemctl --user reset-failed agent-telemetry.service >/dev/null 2>&1 || true
  SERVICE="$HOME/.config/systemd/user/agent-telemetry.service"
  mkdir -p "$(dirname "$SERVICE")"
  cat > "$SERVICE" <<SERVICE
[Unit]
Description=HivemindOS telemetry collector

[Service]
Environment=AGENT_TELEMETRY_PORT=$PORT
Environment=AGENT_TELEMETRY_HOST=$( [[ "$LINK_ACTIVE" == "true" || "$SYSTEM_TAILNET_SERVE_ACTIVE" == "true" ]] && printf "127.0.0.1" || printf "0.0.0.0" )
Environment=AGENT_TELEMETRY_HERMES_API_HOST=$HERMES_API_HOST
Environment=AGENT_TELEMETRY_HERMES_API_PORT=$HERMES_API_PORT
$HERMES_API_KEY_SYSTEMD_ENTRY
Environment=HIVE_COLLECTOR_ONLY=$COLLECTOR_ONLY
ExecStart=$(command -v node) $COLLECTOR
Restart=always

[Install]
WantedBy=default.target
SERVICE
  systemctl --user daemon-reload
  systemctl --user enable agent-telemetry.service
  # Last-moment atomic handover: stop the old instance, clear any stray listener,
  # then start fresh on the new unit. This vulnerable window is now just these
  # adjacent commands, not the whole unit-write/daemon-reload sequence above.
  systemctl --user stop agent-telemetry.service >/dev/null 2>&1 || true
  stop_existing_listener
  systemctl --user restart agent-telemetry.service
  # Collector is back up cleanly; the abort safety-net is no longer needed.
  trap - EXIT

  # Self-heal watchdog: a light timer that re-starts the collector whenever it is
  # found stopped — e.g. an external `systemctl stop`, or an interrupted update on
  # an OLDER build that predates the trap above. `start` is a no-op when it is
  # already running. This gives the Linux collector the same always-up guarantee
  # macOS gets from launchd KeepAlive, so a downed collector self-recovers within
  # minutes without any shell access.
  WATCHDOG_SERVICE="$HOME/.config/systemd/user/agent-telemetry-watchdog.service"
  WATCHDOG_TIMER="$HOME/.config/systemd/user/agent-telemetry-watchdog.timer"
  cat > "$WATCHDOG_SERVICE" <<'WATCHDOG_SERVICE_UNIT'
[Unit]
Description=HivemindOS telemetry collector watchdog
After=agent-telemetry.service

[Service]
Type=oneshot
ExecStart=/bin/sh -c 'systemctl --user is-active --quiet agent-telemetry.service || systemctl --user start agent-telemetry.service'
WATCHDOG_SERVICE_UNIT
  cat > "$WATCHDOG_TIMER" <<'WATCHDOG_TIMER_UNIT'
[Unit]
Description=HivemindOS telemetry collector watchdog timer

[Timer]
OnBootSec=1min
OnUnitActiveSec=3min
AccuracySec=30s

[Install]
WantedBy=timers.target
WATCHDOG_TIMER_UNIT
  systemctl --user daemon-reload
  systemctl --user enable agent-telemetry-watchdog.timer >/dev/null 2>&1 || true
  systemctl --user restart agent-telemetry-watchdog.timer >/dev/null 2>&1 || true
  if [[ "$LINK_ACTIVE" == "true" ]]; then
    prepare_hivemind_link_state_dir
    LINK_SERVICE="$HOME/.config/systemd/user/hivemindos-linkd.service"
    cat > "$LINK_SERVICE" <<SERVICE
[Unit]
Description=HivemindOS embedded Tailscale Link sidecar
After=agent-telemetry.service

[Service]
Environment=HIVE_LINK_TARGET=http://127.0.0.1:$PORT
Environment=HIVE_LINK_LISTEN=:$LINK_TAILNET_PORT
Environment=HIVE_LINK_CONTROL=$LINK_CONTROL
Environment=HIVE_LINK_STATE_DIR=$LINK_STATE_DIR
Environment=HIVE_LINK_LOG_FILE=$LINK_LOG_FILE
Environment=HIVE_LINK_LOG_MAX_BYTES=$LINK_LOG_MAX_BYTES
Environment=HIVE_LINK_TAILSCALE_DEBUG_LOGS=$LINK_TAILSCALE_DEBUG_LOGS
Environment=HIVE_LINK_DISABLE_PORTLIST=$LINK_DISABLE_PORTLIST
Environment=HIVE_LINK_RUN_WEB_CLIENT=$LINK_RUN_WEB_CLIENT
Environment=HIVE_LINK_EPHEMERAL=$LINK_EPHEMERAL
Environment=HIVE_LINK_STATUS_TIMEOUT=$LINK_STATUS_TIMEOUT
Environment=TS_DEBUG_DISABLE_PORTLIST=$LINK_DISABLE_PORTLIST
ExecStart=$LINK_BIN
Restart=always

[Install]
WantedBy=default.target
SERVICE
    start_hivemind_link_service
  else
    echo "HivemindOS collector installed."
  fi
fi

mkdir -p "$HOME/.hivemindos"
{
  printf "AGENT_TELEMETRY_PORT=%q\n" "$PORT"
  printf "HIVE_TAILNET_COLLECTOR_PORT=%q\n" "$TAILNET_COLLECTOR_PORT"
  printf "HIVE_LINK_TAILNET_PORT=%q\n" "$LINK_TAILNET_PORT"
  printf "HIVE_LINK_CONTROL=%q\n" "$LINK_CONTROL"
  printf "HIVE_LINK_STATE_DIR=%q\n" "$LINK_STATE_DIR"
  printf "HIVE_LINK_LABEL=%q\n" "$LINK_LABEL"
  printf "HIVE_LINK_CONTROL_URL=%q\n" "http://$LINK_CONTROL"
  printf "HIVE_LINK_LOG_FILE=%q\n" "$LINK_LOG_FILE"
  printf "HIVE_LINK_LOG_MAX_BYTES=%q\n" "$LINK_LOG_MAX_BYTES"
  printf "HIVE_LINK_TAILSCALE_DEBUG_LOGS=%q\n" "$LINK_TAILSCALE_DEBUG_LOGS"
  printf "HIVE_LINK_DISABLE_PORTLIST=%q\n" "$LINK_DISABLE_PORTLIST"
  printf "HIVE_LINK_RUN_WEB_CLIENT=%q\n" "$LINK_RUN_WEB_CLIENT"
  printf "HIVE_LINK_EPHEMERAL=%q\n" "$LINK_EPHEMERAL"
  printf "HIVE_LINK_STATUS_TIMEOUT=%q\n" "$LINK_STATUS_TIMEOUT"
  printf "HIVE_COLLECTOR_ONLY=%q\n" "$COLLECTOR_ONLY"
  if [[ -n "$HERMES_API_KEY_VALUE" && "$HERMES_API_KEY_VALUE" =~ ^[A-Za-z0-9._~+/=-]+$ ]]; then
    printf "AGENT_TELEMETRY_HERMES_API_KEY=%q\n" "$HERMES_API_KEY_VALUE"
  fi
} > "$HOME/.hivemindos/collector.env"

if [[ "$TAILNET_SYNC_ENABLED" == "true" && "$NETWORK_MANAGED_BY_SETUP" != "true" ]]; then
  install_rsync_if_missing
  maybe_disable_tailscale_shields_up
  enable_tailscale_ssh
fi

if [[ "$NETWORK_MANAGED_BY_SETUP" != "true" && "$LINK_ACTIVE" != "true" ]] && tailscale_status_connected; then
  TAILSCALE_CLI="$(tailscale_cli_candidates | awk '!seen[$0]++ { print; exit }')"
  if [[ -n "$TAILSCALE_CLI" ]]; then
    IP="$(run_tailscale_cli "$TAILSCALE_CLI" ip -4 2>/dev/null | head -1 || true)"
    if [[ -z "$IP" ]]; then
      IP="$(run_tailscale_cli_sudo_noninteractive "$TAILSCALE_CLI" ip -4 2>/dev/null | head -1 || true)"
    fi
    if [[ -n "$IP" ]]; then
      echo "Collector URL: http://$IP:$PORT"
    fi
  fi
fi
if [[ "$LINK_ACTIVE" == "true" ]]; then
  echo "Local collector URL: http://127.0.0.1:$PORT"
  if [[ "$PORT" != "$REQUESTED_PORT" ]]; then
    echo "Hivemind Link Tailnet collector URL remains: http://<this-link-node>:$LINK_TAILNET_PORT"
  fi
  echo "Hivemind Link control URL: $LINK_CONTROL_STATUS_URL"
  echo "Starting Hivemind Link..."
  link_start_attempt=1
  while (( link_start_attempt <= 2 )); do
    if wait_for_hivemind_link_status 20; then
      link_wait_result=0
    else
      link_wait_result=$?
    fi
    LINK_AUTH_URL="$(printf "%s" "$LINK_STATUS" | hivemind_link_auth_url || true)"
    LINK_CONNECTED_NAME="$(printf "%s" "$LINK_STATUS" | hivemind_link_connected_name || true)"
    LINK_BACKEND_STATE="$(printf "%s" "$LINK_STATUS" | hivemind_link_backend_state || true)"

    if [[ -n "$LINK_CONNECTED_NAME" ]]; then
      echo "Hivemind Link connected."
      break
    fi

    if (( link_wait_result == 2 )) || hivemind_link_log_has_stale_identity; then
      if (( link_start_attempt == 1 )); then
        reset_hivemind_link_state
        start_hivemind_link_service
        link_start_attempt=$((link_start_attempt + 1))
        continue
      fi
      echo "Hivemind Link could not finish sign-in automatically. Rerun ./setup.sh and it will try again with fresh Link state." >&2
      break
    fi

    if [[ -n "$LINK_AUTH_URL" ]]; then
      echo "Hivemind Link sign-in required."
      echo "Open this URL on any device to connect this Mac to your Tailscale account:"
      echo "  $LINK_AUTH_URL"
      if wait_for_hivemind_link_auth_confirmation; then
        auth_wait_result=0
      else
        auth_wait_result=$?
      fi
      if (( auth_wait_result == 2 && link_start_attempt == 1 )); then
        reset_hivemind_link_state
        start_hivemind_link_service
        link_start_attempt=$((link_start_attempt + 1))
        continue
      fi
      break
    fi

    if [[ -n "$LINK_BACKEND_STATE" ]]; then
      echo "Hivemind Link is still starting. Setup can continue; the dashboard will keep checking it."
    else
      echo "Hivemind Link did not answer yet. Setup can continue; rerunning ./setup.sh will repair it automatically."
    fi
    break
  done
fi
if wait_for_local_collector 10; then
  if [[ "$LINK_ACTIVE" != "true" ]]; then
    echo "Local collector ready: http://127.0.0.1:$PORT"
  fi
else
  echo "The local collector is still starting. The dashboard will keep checking it." >&2
fi
maybe_enable_system_tailnet_collector_serve
if [[ "$LINK_ACTIVE" != "true" && "$NETWORK_MANAGED_BY_SETUP" != "true" && -n "${IP:-}" ]]; then
  echo "Tailnet reachability check from another dashboard machine:"
  echo "  curl --max-time 5 http://$IP:$PORT/health"
fi
