export const LISTMONK_VERSION = "6.1.0";
export const LISTMONK_IMAGE = "listmonk/listmonk@sha256:179d00d9553c371b6fe88c9b145095d651e275bdd66db46b2e0b79daff316b6f";
export const LISTMONK_POSTGRES_IMAGE = "postgres@sha256:6567bca8d7bc8c82c5922425a0baee57be8402df92bae5eacad5f01ae9544daa";

export function buildListmonkComposeYaml() {
  return [
    "services:",
    "  listmonk:",
    `    image: ${LISTMONK_IMAGE}`,
    "    restart: unless-stopped",
    "    ports:",
    "      - 127.0.0.1:9000:9000",
    "    depends_on:",
    "      postgres:",
    "        condition: service_healthy",
    "    command:",
    "      - sh",
    "      - -c",
    "      - ./listmonk --install --idempotent --yes --config '' && ./listmonk --upgrade --yes --config '' && ./listmonk --config ''",
    "    environment:",
    "      LISTMONK_app__address: 0.0.0.0:9000",
    "      LISTMONK_db__host: postgres",
    "      LISTMONK_db__port: 5432",
    "      LISTMONK_db__user: listmonk",
    "      LISTMONK_db__password: ${LISTMONK_DB_PASSWORD:?Listmonk database password is required}",
    "      LISTMONK_db__database: listmonk",
    "      LISTMONK_db__ssl_mode: disable",
    "      TZ: Etc/UTC",
    "    volumes:",
    "      - listmonk-uploads:/listmonk/uploads",
    "    healthcheck:",
    "      test: [CMD, wget, -q, --spider, http://127.0.0.1:9000]",
    "      interval: 10s",
    "      timeout: 5s",
    "      retries: 12",
    "    logging:",
    "      options:",
    "        max-size: 10m",
    "        max-file: '3'",
    "  postgres:",
    `    image: ${LISTMONK_POSTGRES_IMAGE}`,
    "    restart: unless-stopped",
    "    environment:",
    "      POSTGRES_DB: listmonk",
    "      POSTGRES_USER: listmonk",
    "      POSTGRES_PASSWORD: ${LISTMONK_DB_PASSWORD:?Listmonk database password is required}",
    "    healthcheck:",
    "      test: [CMD-SHELL, pg_isready -U listmonk -d listmonk]",
    "      interval: 10s",
    "      timeout: 5s",
    "      retries: 12",
    "    volumes:",
    "      - listmonk-postgres:/var/lib/postgresql/data",
    "    logging:",
    "      options:",
    "        max-size: 10m",
    "        max-file: '3'",
    "volumes:",
    "  listmonk-uploads:",
    "  listmonk-postgres:",
    "",
  ].join("\n");
}
