import { NextResponse, type NextRequest } from "next/server";
import { unauthorizedJson, verifyAuth } from "@/lib/utils/server-auth";

// Next 16 with a src/ layout only loads this file from src/proxy.ts (or
// src/middleware.ts, deprecated) — a root-level middleware.ts is silently
// ignored, which left every /api route without this gate until 2026-07-03.
const SELF_AUTHENTICATING_API_PREFIXES = [
  "/api/auth/session",
  // Passkey status/options/verification are part of the lock ceremony. The
  // authentication verifier issues a session only after a one-use WebAuthn
  // challenge succeeds; registration and management routes still call
  // requireAuth themselves and remain closed while locked.
  "/api/auth/passkeys",
  // Browser-extension preflights cannot carry dashboard credentials. The route
  // handles CORS and verifies the dashboard device token on every GET/POST.
  "/api/browser-extension",
  "/api/runtimes/aeon/brain",
  "/api/runtimes/aeon/hive/miroshark",
  // Authenticates inside the route: dashboard auth OR a path-scoped signed URL
  // (phone image loaders can't carry the session cookie / device token).
  "/api/chat/generated-media",
  // Public seller endpoints for EXTERNAL buyers: payment is the auth (x402
  // settlement or X-HivemindOS-Credit-Token), never fleet credentials. The
  // x402 handshake requires the first request to arrive credential-less so the
  // resource server can answer with the 402 payment challenge; a dashboard
  // gate in front dead-ends the revenue rail. The routes fail closed on their
  // own: seller-mode/enabled/config checks and payment verification run before
  // any runtime work, and the official-* routes only relay allowlisted payment
  // headers to the hosted gateway, which enforces payment upstream.
  "/api/paid-agents",
  "/api/official-paid-agents",
  // Stripe webhooks: the Stripe-Signature HMAC verified inside each route is
  // the auth (fail-closed without the shared secret); Stripe cannot carry
  // dashboard credentials. Before 2026-07-16 the managed-agent webhook was
  // missing here, so Stripe's POST dead-ended at this gate with a 401.
  "/api/managed-agent/billing/stripe-webhook",
  "/api/company-revenue/stripe-webhook",
  // OAuth callbacks authenticate with a signed `state` generated by an
  // authenticated dashboard start request. The external browser often lacks the
  // dashboard session cookie, so the proxy must let the callback route verify
  // state and exchange the provider code itself.
  "/api/integrations/google/oauth/callback",
  "/api/integrations/google-cloud/oauth/callback",
  "/api/integrations/robinhood-mcp/callback",
  // Managed X OAuth returns through the external browser, which cannot carry
  // the Tauri webview session. This route only records a short-lived local
  // receipt; the authenticated desktop app polls a separate protected route.
  "/api/integrations/x-managed/desktop-return",
  // Local brain bridge for hivemindos.app mini-apps: the browser page cannot
  // carry dashboard credentials cross-origin. hello is a harmless presence
  // probe; recall is READ-ONLY; skill and artifact are bounded writes,
  // fail-closed audited inside their routes. All four verify a
  // dedicated bridge token inside the route (or fall back to dashboard auth).
  // The token-mint route (/api/research-bridge/token) is deliberately NOT
  // listed — it stays behind this gate.
  "/api/research-bridge/hello",
  "/api/research-bridge/recall",
  "/api/research-bridge/skill",
  "/api/research-bridge/artifact",
];

function isSelfAuthenticatingApi(pathname: string) {
  return SELF_AUTHENTICATING_API_PREFIXES.some((prefix) => pathname === prefix || pathname.startsWith(`${prefix}/`));
}

export async function proxy(request: NextRequest) {
  if (!request.nextUrl.pathname.startsWith("/api/")) return NextResponse.next();
  if (isSelfAuthenticatingApi(request.nextUrl.pathname)) return NextResponse.next();

  const auth = await verifyAuth(request);
  if (!auth.userId) return unauthorizedJson(auth.reason);
  return NextResponse.next();
}

export const config = {
  matcher: ["/api/:path*"],
};
