import { NextResponse, type NextRequest } from "next/server";
import { unauthorizedJson, verifyAuth } from "@/lib/utils/server-auth";

// Next 16 with a src/ layout only loads this file from src/proxy.ts (or
// src/middleware.ts, deprecated) — a root-level middleware.ts is silently
// ignored, which left every /api route without this gate until 2026-07-03.
const SELF_AUTHENTICATING_API_PREFIXES = [
  "/api/auth/session",
  "/api/runtimes/aeon/brain",
  "/api/runtimes/aeon/hive/miroshark",
  // Authenticates inside the route: dashboard auth OR a path-scoped signed URL
  // (phone image loaders can't carry the session cookie / device token).
  "/api/chat/generated-media",
  // Public seller endpoints for EXTERNAL buyers: payment is the auth (x402
  // settlement or X-HivemindOS-Credit-Token), never fleet credentials. The
  // x402 handshake requires the first request to arrive credential-less so the
  // resource server can answer with the 402 payment challenge; a dashboard
  // gate in front dead-ends the revenue rail. The routes fail closed on their
  // own: seller-mode/enabled/config checks and payment verification run before
  // any runtime work, and the official-* routes only relay allowlisted payment
  // headers to the hosted gateway, which enforces payment upstream.
  "/api/paid-agents",
  "/api/official-paid-agents",
  // OAuth callbacks authenticate with a signed `state` generated by an
  // authenticated dashboard start request. The external browser often lacks the
  // dashboard session cookie, so the proxy must let the callback route verify
  // state and exchange the provider code itself.
  "/api/integrations/google/oauth/callback",
  // Managed X OAuth returns through the external browser, which cannot carry
  // the Tauri webview session. This route only records a short-lived local
  // receipt; the authenticated desktop app polls a separate protected route.
  "/api/integrations/x-managed/desktop-return",
];

function isSelfAuthenticatingApi(pathname: string) {
  return SELF_AUTHENTICATING_API_PREFIXES.some((prefix) => pathname === prefix || pathname.startsWith(`${prefix}/`));
}

export async function proxy(request: NextRequest) {
  if (!request.nextUrl.pathname.startsWith("/api/")) return NextResponse.next();
  if (isSelfAuthenticatingApi(request.nextUrl.pathname)) return NextResponse.next();

  const auth = await verifyAuth(request);
  if (!auth.userId) return unauthorizedJson(auth.reason);
  return NextResponse.next();
}

export const config = {
  matcher: ["/api/:path*"],
};
