export const USEPOD_COMPUTE_RENTALS_FLAG_ENV = "NEXT_PUBLIC_HIVEMINDOS_USEPOD_COMPUTE_RENTALS_ENABLED";

export const USEPOD_COMPUTE_RENTALS_ENABLED =
  process.env.NEXT_PUBLIC_HIVEMINDOS_USEPOD_COMPUTE_RENTALS_ENABLED === "1" ||
  process.env.NEXT_PUBLIC_HIVEMINDOS_USEPOD_COMPUTE_RENTALS_ENABLED === "true";
